cli.bat
cli script that works on a windows OS
=> cli bata file

sefaria/utils/hebrew.py
=> another translation

templates/js/headers.js
Please make sure I did this right. This is my first real pull request. :)
=> modified autocomplete to return only 15 titles (#3 in list of changes)

sefaria/client/util.py, sefaria/views.py
See https://code.djangoproject.com/ticket/3526 - content_type is a
little more modern and mime_type is potentially "something that should
be removed in the future"
=> content_type instead of mimetype

data/tmp/rename Ben Ish Hai.csv
looks like a problem with the encoding i changed to UTF-8 with no BOM
=> renaming csv

sefaria/client/util.py, sefaria/views.py
Reverts blockspeiser/Sefaria-Project#161
=> Revert "content_type instead of mimetype"

static/css/sheets.css, static/js/sheets.js, templates/sheet.html, templates/sheets.html
Language & layout can now be modified on an individual source basis instead of only at the sheet level.
Also fixed this bug: https://sefaria.slack.com/archives/live-bugs/p1442610715000002
=> Add ability to apply custom layout to individual sources on Source Sheets

static/js/reader.js
just changed:
data.title == "Sefer Mitzvot Gadol";
=> Sefer Mitzvot Gadol instead of SeMaG

sefaria/utils/hebrew.py
=> added hebrew translations of section names

static/js/sheets.js
=> hotfix alignment and direction of an outsideText that is in Hebrew

sefaria/helper/schema.py
=> helper schema replaceBadNodeTitles

sefaria/model/schema.py, sefaria/model/tests/schema_test.py
Do not merge this branch before running the script to remove non ascii characters from primary English titles
=> Ascii check

scripts/add_is_cited_field.py, sefaria/model/text.py
This doesn't affect any behavior, but allows for population of citation white-list before citations are limited to white listed texts only.
=> Optional parameter "is_cited" on index, script to add parameter.

scripts/standardize_rambam.py, sefaria/model/history.py, sefaria/model/link.py, sefaria/model/tests/index_test.py, sefaria/model/tests/text_test.py, sefaria/model/text.py, sefaria/system/database.py
Standardizing the Rambam titles required a more efficient cascading process.
=> Make index change cascading more efficient; standardize Rambam titles.

static/js/ConnectionsPanel.jsx, static/js/LexiconBox.jsx
=> only activate lexicon box if selected text contains hebrew

static/css/s2.css
Icons in headers, search filters, and inactive search count made darker by 20%
=> Icons and search color changes

sefaria/model/__init__.py, sefaria/model/lexicon.py
=> Add type to lexicon

scripts/seferhamitzvotquality.py
Changes to "Sefer HaMitzvot LaRambam" index, its nodes, and to its commentaries
=> Sefer hamitzvot larambam

sefaria/model/__init__.py, sefaria/model/lexicon.py, sefaria/model/text.py
See Berachot 1:5 in this [text](https://www.sefaria.org/Maaseh_Nissim_on_Pesach_Haggadah%2C_Magid%2C_Story_of_the_Five_Rabbis.2.1?ven=Rabbi_Mark_Greenspan&lang=en) and it incorrectly resolves to Talmud
Also other fixes from master
@EliezerIsrael
=> Fix english talmud ref wrapping

sefaria/model/schema.py
@EliezerIsrael 
don't like it and its not in the right place, but displays data (too sparsely) and don't want to get ahead of myself here before discussing a bit more
=> Not clean but displays all data, to be fine-tuned and moved

sefaria/model/lexicon.py
fix <hw-number>IV</hw-number>, see אָדָא IV for example
@EliezerIsrael
=> Fix V in hw number

scripts/nechama_alt_titles.py
in order that spellings of names be consistent
=> needs to be run both locally and on production/sandbox

sefaria/model/schema.py
=> Add sof, reish and b'daf

sefaria/sheets.py, sourcesheets/views.py
This merge will allow adding new groups by API. It also allows a sheet's nodes to be rebuilt by setting a "rebuildNodes" flag when POSTing a sheet via API.
=> Groups api and Flag to build nodes on sheet API POST

sefaria/model/schema.py
I fixed a missing parenthesis in the regex for AddressSection that was causing an error.
=> Fixed AddressSection regex

static/js/Header.jsx
when click on search and there isn't a query, focus the search box.
this is the expected behaiver
=> focus the search box on click empty search

scripts/topics_graph_validation.py
=> graph retroactive validation script and the getattr for the topic nodes validation in the model

sefaria/model/text.py
Reverts Sefaria/Sefaria-Project#548
=> Revert "Cleanup: Inline conditional that is always true"

sefaria/model/text.py
This change removes an `if` statement that is always `True` (the `or True` clause causes the result to always be true, even if `not self._spanned_refs` is false.
The rest of the change is simply outdenting the code that was previously nested inside the `if`.
This is a second try at https://github.com/Sefaria/Sefaria-Project/pull/548, with a fix to one small typo.
@JonMosenkis @EliezerIsrael - running `git diff 35ffb5598988e1bb902534178c170ca9aeb2fe0f` produces:
```patch
- d["toSections"] += [self.get_state_ja().sub_array_length([s - 1 for s in d["toSections"][0:i]],until_lnonempty=True)]
+ d["toSections"] += [self.get_state_ja().sub_array_length([s - 1 for s in d["toSections"][0:i]],until_last_nonempty=True)]
```
=> Cleanup: Inline conditional that is always true

README.mkd, sefaria/model/autospell.py, sefaria/model/text.py
Created using `sed -i s/blockspeiser/Sefaria/g "$(gg -l blockspeiser)"`
=> Use Sefaria/Sefaria-Project github instead of blockspeiser/Sefaria-Project

README.mkd
There was a imperceptible typo in README.mkd
=> Fix a typo

templates/static/linker.html
"gives makes" should be just "makes"
=> Fix typo in linker.html

templates/js/linker.v2.js
added fancy quotes to the quotation regex in Linker
=> added fancy quotes to the quotation regex in Linker

reader/views.py, sefaria/model/link.py
A link post must now have a "contents" field, where the link or links go, and can also have "_skip_lang_check" field.  If we keep this code, I will need to change the API documentation.
=> sanitize faster and skip_lang_check in post

sefaria/datatype/jagged_array.py, sefaria/model/text.py, sefaria/utils/hebrew.py
This is more for the discussion than for actual change.
As someone new to Sefaria, I find some of the code to be very abstruse.
A big part of this is the lack of typing in both the parameters that functions receive and their return values.
This PR is more of a question: are you open to adding type annotations to the code? They make the code much more immediately readable, especially if you're using a powerful (read: Jetbrains) IDE like Pycharm which understands, and can infer from, type annotations.
I'm starting with some obvious things, but if you're okay with this I hope to continue to some of the stranger functions.
=> Type annotations

static/js/ReaderApp.jsx, templates/js/chavruta.js
Fix extra comma issue in chavruta sources
=> Chavruta iteration 2

scripts/cauldron_links.py, scripts/cauldron_text.py, static/js/Footer.jsx
Adds "Learning Schedules" to footer
Contains current versions of cauldron breaking scripts.
=> added calendars to footer

static/css/s2.css, static/js/UserProfile.jsx
https://trello.com/c/e68NIoNI/13-front-end-saves-custom-schedule-data-to-db
=> Learning schedules frontend post

static/js/UserProfile.jsx
https://trello.com/c/HVdqxWBY/22-attempting-to-use-the-search-field-creates-whitescreen
=> Learning schedules search bug

sefaria/helper/schema.py
=> needs_rewrite sometimes takes two argument and other times one. 

.github/workflows/continuous.yaml, .github/workflows/image-builder.yaml
- updates current per-push testing workflow to only run against commits in PR
- Adds new workflow to build and push images to GCR for each commit (to be hooked into cauldron creation and testing pipelines
Currently only pushes to dev, in future we can add an additional step to push to the prod registry on commits to master
=> Per branch image build

static/css/s2.css, static/js/ReaderApp.jsx, static/js/SearchResultList.jsx, static/js/sefaria/strings.js
Only remaining issue is the small Hebrew font on search page that is a problem independent of this project.
=> Searchtopics

sefaria/model/following.py, sefaria/model/user_profile.py
=> Follow recommendation fixes

helm-chart/templates/configmap/local-settings.yaml
Added new setting to localsettings.yaml in preparation for new feature launch.
=> add ml model settings

.github/workflows/helm-release.yaml
Created github pages branch using: https://gist.github.com/ramnathv/2227408
@edamboritz @EliezerIsrael if theres a need for consistent branding for all aspects of Sefaria you can set up themes: https://docs.github.com/en/pages/quickstart
You probably also want to check that any other github pages settings are to your preference.
=> ci: add pipeline to publish helm charts

helm-chart/sefaria-project/templates/configmap/local-settings-monitor.yaml, helm-chart/sefaria-project/templates/configmap/local-settings-nginx.yaml, helm-chart/sefaria-project/templates/configmap/local-settings-node.yaml, helm-chart/sefaria-project/templates/configmap/local-settings-web.yaml, helm-chart/sefaria-project/templates/rollout/monitor.yaml, helm-chart/sefaria-project/templates/rollout/nginx.yaml, helm-chart/sefaria-project/templates/rollout/nodejs.yaml, helm-chart/sefaria-project/templates/rollout/web.yaml, helm-chart/sefaria-project/values.yaml
start of the preparatory hooks to allow pod specific localsettings to enable testing of linker
=> feat: allow web specific localsettings overrides

static/js/ConnectionsPanel.jsx
Merge @nissamai's bug fix into `master` instead of `test`
=> Source sheet history

scripts/nation_builder_sync.py
so that bad/spam emails in mongo don't get added to nb
=> fix: don't sync profiles to nb every time script gets run

sefaria/helper/descriptions.py
=> Descriptions script fix

.github/workflows/production-deploy.yaml, .github/workflows/release.yml
- add username of release trigger to release info
- prevent commenting on PRs/issues
- explicitly use conventional-commits
- allow release to call production deployment
=> fix: various improvements to workflow pipeline

build/node/Dockerfile, build/web/Dockerfile
Change tags references to base containers in node and web container docker files
=> docker files

sefaria/settings.py
Remove elul sustainer modal from site
=> feat(modals): remove sustainer modal

sefaria/model/text.py
Fleshing out the documentation for `Version` and `VersionSet`.
=> Adding some examples to Version and VersionSet

sefaria/model/text.py
Fixing minor typos in the docstrings of text.py.
=> Fixing typos

.github/workflows/production-deploy.yaml
workaround for https://github.com/Azure/setup-helm/issues/97
=> fix: hardcode helm deployment version

reader/views.py, sefaria/helper/topic.py
Add a special function for topic pages which always forces Django to get the time period. Addressing the bug on [this](https://trello.com/c/HQ4L7Ky5/2830-topic-pages-for-talmudic-figures-dont-always-display-life-span-even-when-available-in-db) card.
=> Bugweek talmudic lifespan

static/js/SearchPage.jsx
Replacing backwards quotes for more correct Hebrew straight quotes. Addressing [this](https://trello.com/c/7aHW27uq/2850-hebrew-search-quote-issues) card.
=> Hebrew Search Quote Issue

static/js/SearchResultList.jsx, static/js/sefaria/search.js
Solves the problem in the original Trello card as well as this issue: https://trello.com/c/8C9HAFd7/2814-search-results-page-behaves-strange-when-going-back-from-individual-result-sources#comment-636bae855a48750187e05ac3
=> Search sort and number off upon reloading page

static/js/SearchFilters.jsx
=> fix: show topic filter in hebrew interface; show collections with hebrew title

static/js/ReaderApp.jsx
fix sheet filter disappearance after rehitting enter https://trello.com/c/NCFHZzZN
=> fix: change wrong var names

static/js/ConnectionsPanel.jsx
=> fix: make webpages filter keyboard accessible

static/js/Promotions.jsx, static/js/ReaderApp.jsx
This commit addresses: https://trello.com/c/4eOorsZq/
=> fix(Promotions): Make keywords on in-app ads sheets case-insensitive

reader/views.py, static/js/ConnectionFilters.jsx, static/js/ConnectionsPanel.jsx, static/js/ReaderApp.jsx
https://trello.com/c/1gqvdtFB/
=> Bugweek connection panel state

static/js/NavSidebar.jsx
Remove extra quotation mark from Hebrew about topic.
=> Remove extra quotation mark

helm-chart/sefaria-project/templates/configmap/local-settings-file.yaml, helm-chart/sefaria-project/values.yaml, sefaria/system/context_processors.py, templates/base.html
All and only the changes to move from GTM pushing to the data layer to gtag pushing to the data layer.
=> feat(GA4): gtag script for GA

static/js/SearchFilters.jsx, static/js/sefaria/strings.js
https://trello.com/c/YFHPD62h/2847-see-more-on-search-not-translated
=> fix: translation for "see More"

sefaria/helper/linker.py, sefaria/model/linker/ref_resolver.py, sefaria/model/linker/referenceable_book_node.py, sefaria/model/linker/tests/linker_test.py, sefaria/model/schema.py, sefaria/model/text.py, static/js/linker.v3/main.js
Reverts Sefaria/Sefaria-Project#1147
=> Revert "Linker v3"

sefaria/settings.py, static/mobile/message-en.json, static/mobile/message-he.json, templates/messages/2022-12-18-end-of-year-msg03-banner.html
=> Eoy fundraiser 3

sefaria/settings.py, static/mobile/message-en.json, static/mobile/message-he.json, templates/messages/2022-12-18-end-of-year-msg03-banner.html, templates/messages/2022-12-22-end-of-year-msg04-banner.html
=> Eoy fundraiser 4

sefaria/model/linker/match_template.py, sefaria/model/linker/referenceable_book_node.py, sefaria/model/schema.py
(branch name ended up not matching work done on the branch)
=> Refactor MatchTemplateTrie for readability

static/js/BookPage.jsx
https://trello.com/c/TBDpko48/2860-commentary-link-in-book-toc-doesnt-take-you-to-commentary-in-text-toc
=> Commentary link broken

scripts/delete_spam_users.py, sefaria/sheets.py, sefaria/views.py
https://trello.com/c/WW3YdYHv/29-implement-new-spam-user-deletion-workflow
=> Spam users quarantine sheets delete

sefaria/model/topic.py
Also restores the use of this exception in Topic.merge().
=> fix(topics): Add missing exception import

sefaria/model/topic.py
Fixes the issue that duplicate links can appear on an author page. E.g. here: https://www.sefaria.org/topics/isaiah-dtrani?tab=sources
=> Fix double books author page

scripts/nation_builder_tags.py
Trivial update to this script to put the date of output in the outf since we're running it for other multiple times
=> chore(crm-scripts): Update tag output script to print the date

static/js/LexiconBox.jsx
fixes this - https://trello.com/c/rKlAWeFk/2888-visible-code-in-bdb-dictionary-entries
=> fix: wrap bdb's headword_suffix in dangerouslySetInnerHTML.

static/js/ReaderApp.jsx, static/js/sefaria/FilterNode.js, static/js/sefaria/searchState.js, static/js/sefaria/util.js
=> Fix search filter bug

static/js/AboutBox.jsx, static/js/ConnectionsPanel.jsx, static/js/ReaderApp.jsx, static/js/TranslationsBox.jsx, static/js/VersionBlock.jsx
Fix for this bug https://trello.com/c/Exf6GEXN
=> Fix translations selecting

templates/static/he/team.html
=> static(team-he): update team page to nissa's headshot

.gitignore, sefaria/settings.py, static/mobile/message-en.json, static/mobile/message-he.json, templates/messages/2023-04-02-passover-donate-banner.html
* Resolves https://trello.com/c/nqppV0nR
* Example: ![](https://user-images.githubusercontent.com/14145322/228650756-3c5eac92-3645-4bf9-91f4-0cb524034688.png)
* Desktop hebrew and mobile versions were not tested
=> Setup banner for Pesach fundraising

templates/static/jobs.html
Non-urgent static change; whoever sees this first can review.
https://trello.com/c/D7gu08YM
=> Jobs update

static/js/ReaderApp.jsx, static/js/sefaria/util.js
Reverts Sefaria/Sefaria-Project#1377
=> Revert "Bug: fix copy past for non html elements"

static/css/s2.css, static/js/Header.jsx
https://trello.com/c/DXwCj2KE/2909-donate-button-in-mobile-web-menu
=> Move donate button on mobile web

templates/static/jobs.html
Resolves
* https://trello.com/c/lv3cmTmC
* https://trello.com/c/3SoOMW59
* https://trello.com/c/Oc956HV5
=> Removes closed positions from jobs page and shows no jobs available

sefaria/views.py
Fixes https://github.com/Sefaria/Sefaria-Project/issues/1387
=> Support selecting versions in /api/bulktext. 

helm-chart/sefaria-project/templates/configmap/local-settings-file.yaml, helm-chart/sefaria-project/templates/configmap/local-settings.yaml, package-lock.json, package.json, requirements.txt, sefaria/local_settings_example.py, sefaria/settings.py, sefaria/system/context_processors.py, static/js/ReaderApp.jsx, templates/base.html
Reverts Sefaria/Sefaria-Project#1409
=> Revert "Server rollbar integration 2"

sefaria/helper/crm/crm_connection_manager.py, sefaria/helper/crm/crm_mediator.py, sefaria/helper/crm/dummy_crm.py, sefaria/helper/crm/nationbuilder.py, sefaria/helper/crm/salesforce.py, sefaria/helper/crm/tests/crm_mediator_test.py, sefaria/model/user_profile.py, sefaria/utils/user.py
Adds functionality to mark users in CRM when deleted.
https://app.shortcut.com/sefariatest-1/story/6084/
=> Crm 6084 - mark delete

sefaria/settings.py, templates/messages/2023-06-16-help-center.html
Story details: https://app.shortcut.com/sefaria/story/6006
=> chore: [sc-6006] Help Modal for Learning team

sefaria/forms.py, sefaria/urls.py, sefaria/utils/user.py, sefaria/views.py, templates/registration/delete_user_account.html
https://github.com/Sefaria/Sefaria-Project/compare/6016-self-service-delete
=> 6016 self service delete

sefaria/settings.py
Story details: https://app.shortcut.com/sefaria/story/18644
=> chore: [sc-18644] Take down Help Modal for Learning team

static/css/s2.css, static/js/Header.jsx
https://app.shortcut.com/sefaria/story/19135/quick-win-logged-in-desktop-web-users-always-see-help-navigation
=> Help button

static/js/Misc.jsx, static/js/Promotions.jsx, static/js/context.js
Adds markdown and hebrew support for modals and banners. Support for sidebar ads/promotions still needs to be completed.
=> Feature/sc 19551/add hebrew markdown support to modals banners

scripts/export_users_not_in_salesforce.py
(same as with other PR you can do this next week)
=> feat(script): output users with no salesforce id into csv [sc-6111]

sites/sefaria/urls.py, templates/messages/2023-08-01-tu-b-av.html
Story details: https://app.shortcut.com/sefaria/story/19062
=> chore: [sc-19062] Create URL at sefaria.org/gala that goes to some to be determined classy page

templates/static/en/team.html, templates/static/he/team.html
Story details: https://app.shortcut.com/sefaria/story/19873
=> chore: [sc-19873] Update Samantha Shokin on Team Page

sefaria/settings.py, static/mobile/message-en.json, static/mobile/message-he.json
Story details: https://app.shortcut.com/sefaria/story/19836
=> chore: [sc-19836] Remove Tu B'av Banner

static/js/Misc.jsx
hot fix didn't import react correctly
=> fix(gtag): hotfix gtag

static/js/Misc.jsx
Added back in the functionality to collect some data on tooltipped clicks for topic pages.
=> Ga4 struct

static/js/Misc.jsx
Story details: https://app.shortcut.com/sefaria/story/20034
=> chore: [sc-20034] Update header donate buttons

static/css/s2.css, static/js/TextsPage.jsx
Story details: https://app.shortcut.com/sefaria/story/19894
=> chore: [sc-19894] Allow HTML in dedications in TOC

sefaria/model/webpage.py, static/js/linker.v3/main.js
This PR allows the linker to be run on a local HTML file. This is useful when testing the linker locally.
=> Allow linker from local webpage

.github/workflows/helm.yaml, .github/workflows/release.yml
https://github.com/semantic-release/commit-analyzer/issues/517
=> ci: re-pin semantic plugin

sefaria/constants/model.py, static/css/s2.css, static/js/ReaderApp.jsx, static/js/ReaderPanel.jsx, static/js/TextColumn.jsx, static/js/TextRange.jsx
allow for book to contain links to the same book and upon clicking, scroll to the new ref instead of opening new panel
=> feat(Scroll Links): inline links can now be scrollLink or refLink

static/js/SearchTextResult.jsx
Normalize ref if Sefaria.parseRef can't find if the index
=> feat(Search Results): Normalize ref

templates/static/en/team.html, templates/static/he/team.html, templates/static/jobs.html
Story details: https://app.shortcut.com/sefaria/story/20667
=> chore: [sc-20667] Update Job

README.mkd
This Pull Request fixes a typographical error in the README.md file.
Corrected "compatability " to "compatibility" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
=> remove typo

sefaria/model/topic.py
when birthPlace doesnt correspond to a Place in our DB
=> fix(Topic Editor): fail gracefully 

helm-chart/sefaria-project/templates/configmap/create-mongo-dumps.yaml
This PR removes a collection that serves as a cache backend from the persistent data backup
=> helm(fix): Remove collection not needed for database backup

sefaria/model/version_state.py
chore: Update VersionState Docs
=> chore: Update VersionState Docs

scripts/parse_rambi_webpages.py, sefaria/helper/linker.py, sefaria/model/linker/linker.py, sefaria/model/linker/named_entity_resolver.py, sefaria/model/linker/ref_resolver.py, sefaria/model/linker/resolved_ref_refiner.py, sefaria/model/linker/tests/linker_test.py, sefaria/model/text.py
Internal PR to ner-model branch to control a somewhat complicated refactor. This PR is not to master.
=> Ner model2

templates/static/jobs.html
Remove Communication Specialist job and set page back to have no jobs listed
=> Remove Communication Specialist job

static/css/s2.css, static/js/Header.jsx
1. moved magnifying glass to be under the main search box
2. moved line underneath the search for: "X" with magnifying glass before the rest of the list
=> Magnifying glass to top of search

reader/views.py, sefaria/model/tests/chunk_test.py, sefaria/model/text.py
Fixes https://github.com/Sefaria/Sefaria-Project/issues/1724
=> Detect TextFamily with underscores everywhere. 

static/css/s2.css
=> chore(ProfilePicIcon): aligned default and non-default profile pic button

templates/gdocs_sheet.html
solves an issue with kamatz katan in exporting to google docs
=> fix(export sheet to google): change hebrew font to Noto Serif Hebrew.

static/js/VersionBlock/VersionBlock.jsx, static/js/sefaria/sefaria.js
=> Deprecate isBaseText

sefaria/model/schema.py, sefaria/model/topic.py
Also add docs to `Topic.merge`
=> fix: Fix recursion call in `TreeNode.traverse_tree`.  

static/js/Footer.jsx
Update the footer links to refer to the updated links.
=> Update footer links

static/js/StaticPages.jsx
This changes the "Sponsor a Text" box to be for "Giving Circles" instead
=> "Giving Circle" Link for Gala

templates/edit_profile.html, templates/sheets.html
Story details: https://app.shortcut.com/sefaria/story/25534
=> chore: [sc-25534] xss attack vulnerability #2

static/js/TopicPage.jsx
Readd previously removed sections of the steinsaltz portal
=> feat(topics): Fully activate all portions of steinsaltz portal

static/js/sefaria/sefaria.js
Ramban on Genesis, Introduction should not redirect to Genesis, Introduction.  Instead clicking on it from the TOC should send you to Ramban on Genesis, Introduction.  I also caught a potential other bug whereby the parsedRef cache was being modified via the variable 'commRef' whereas the copy of the object 'commRef', 'commRefCopy' should be modified instead.
My reason for putting the check in `isCommentaryRefWithBaseText` because it will prevent any attempt to convert "Ramban on Genesis, Introduction" since `openPanelAt` directly calls `isCommentaryRefWithBaseText` to determine whether to convert the ref.  I could've put this check in the actual conversion code (i.e. sefaria.js's `convertCommentaryRefToBaseRef`) and then had it fail but I think this would overly complicate the code.
=> fix(Commentary Redirects): Ramban on Genesis, Introduction

static/js/LexiconBox.jsx
Need to remove since other things besides rabbis can be ambiguous.
=> fix(ner): remove "rabbis" from ambiguation description.

static/css/s2.css, static/js/Misc.jsx, static/js/TopicPage.jsx
recent fixes for the aiInfoTooltip
=> Topic prompt generator fixes

build/ci/production-values.yaml
Master_name chart value had a typo in it.
=> fix(llm): fix typo to master_name

templates/static/supporters.html
Adds new supporters to Builders and Innovators sections
=> Update to Supporters page

sefaria/search.py
to not include some versions vs to only include those 2 versions.
=> fix(search): Fixing search

scripts/scheduled/reindex_elasticsearch_cronjob.py, sefaria/pagesheetrank.py
This is an error caused when trying to calculate `Ref.range_list()` on a ref with a broken version.
In addition, this removes the cronjob reporting.
=> Catch state node keyerror

static/js/sheets.js
This should help make the english hey replacement better so that it reads properly
=> Make the hey replacement have a hebrew geresh instead of a single quote

sefaria/helper/llm/topic_prompt.py
Add two parameters to `make_topic_prompt_source` to make the function a bit more flexible. Also, make `make_topic_prompt_source()` and `make_llm_topic()` public so they can be reused.
=> Updates to topic prompt source

sefaria/helper/topic.py
To temporarily solve admin issues with topic page editing, we will only allow editing of learning-team links
=> Only edit learning team links

static/css/s2.css, static/js/SearchResultList.jsx, static/js/SearchSheetResult.jsx
Re-factored SearchSheetResult so that it receives props `metadata` and `snippet`.  Also modified the way it displays in line with the modularization design by re-arranging the order of the components, removing the ColorBarBox, and adding a date.
=> Feature/sc 28260/re factor sheetsearchresult

static/js/linker.v3/popup.js
Fix - title was shown in English, if contentLang was set to 'hebrew'. 
When ctrl + click is triggered open in new tab.
=> Update linker.v3/popup.js 

sefaria/model/tests/text_test.py
Also, refactor test so data is pulled out.
Title of Ibn Ezra on Exodus was changed to "Ibn Ezra on Exodus; Perush HaArokh".
=> test(library): fix failing test due to title change of Ibn Ezra.

static/js/Misc.jsx
small additional fix to complement previous PR
=> Display disambiguation in brackets also for non-primary titles

templates/base.html
The Unbounce embed script has been added. Banners and Modals will be done through Unbounce for the trial's duration.
=> Add Unbounce

sefaria/helper/tests/topic_test.py, sefaria/helper/topic.py, sefaria/model/place.py
fixed tests to reflect new implementation of update_topic, also made the kwargs of this function explicit
=> Bug/sc 28708/fix usage of update topic

sites/sefaria/urls.py, static/js/StaticPages.jsx, templates/static/the-sefaria-story.html
Development has requested that additional **channel source codes** parameters be added to and changed on donation links to track the distribution channel for where users are coming from for specific campaigns. The donation links also  now have the short name `english` instead `en` as Classy is unable to support using `en` as a short name for a campaign.
=> Donation Links Updates

helm-chart/sefaria-project/templates/configmap/local-settings-file.yaml, sefaria/local_settings_example.py, sefaria/urls.py
Changes the admin site for Django to point to a non default path
=> Change certain url paths

static/js/Misc.jsx
Two links were changed for the AI info tooltip to go to a different sheet
=> Update links in AI info tooltip

static/js/CommunityPage.jsx, static/js/NavSidebar.jsx, static/js/TopicPageAll.jsx, static/js/TopicsPage.jsx
As part of modularization, we are removing the "JoinTheConversation" module.
I've removed it from NavSidebar.jsx and several places in the code that reference this module
=> chore: remove nav sidebar module JoinTheConversation

.github/workflows/continuous.yaml
=> feat: create overarching branch protection check

.github/workflows/continuous.yaml
=> ci: trigger pipeline rerun on draft change

.github/workflows/continuous.yaml
=> fix: put pull request triggers in pull request settings

.github/workflows/continuous.yaml
=> fix: put back old interdepencies

static/js/Promotions.jsx, static/js/ReaderApp.jsx, static/js/context.js
Re-enable Strapi for banners and modals
=> Resurrection of Strapi

static/js/ReaderPanel.jsx
This PR fixes bad spellings of sheets directory imports.
=> chore: fix spelling in reader panel of sheets directory

.github/workflows/release.yml
=> fix: bump semantic plugin version

.github/workflows/integration-testing.yaml
=> ci: don't skip on manual workflow

build/linker/Dockerfile, static/js/sefaria/sefaria.js
Fix for pages like this https://www.sefaria.org.il/topics/machloket-lshem-shamayim?tab=admin where there are only notable sources and no non-notable sources
Assumption in processTopicsData() was that the "sources" tab exists if there are notable sources. Now we check that that's true.
=> Fix topic page empty sources

static/js/UserProfile.jsx
Youtube profile does not add prefix to link properly
add youtube url as prefix to handler
=> fix(profile): fix broken youtube link on profile

static/js/TopicPage.jsx, static/js/sefaria/sefaria.js
This PR fixes previous attempt at this hack by relying on the loaded topic data instead of the html elements on screen
=> Fix auto redicreciton of sourceless topic pages to sheets search results

sefaria/model/schema.py
=> fix(linker): match פס without a geresh afterwards

static/js/TopicPage.jsx, static/js/sefaria/sefaria.js
Revert for PR https://github.com/Sefaria/Sefaria-Project/pull/2080/files
=> fix(topics): revert bug created by pr 2080 where many topic pages go to search

static/js/TopicPage.jsx
prevent redireciton for authoer pages
also, when a title is missing for one language, fall back on the other one to generate the search query
=> Fix redirection for hebrewless topic pages and author topic pages

static/js/Misc.jsx
=> Update AI Message

static/js/linker.v3/main.js
=> Fix dup ref wrapping

sefaria/model/linker/tests/linker_test.py, sefaria/model/schema.py
Gives the ability to linker to parse references that use roman numerals
Adds a parameter to how AddressInteger address types are recognized to also recognize roman numerals
=> feat(linker): allow parsing of roman numerals

templates/_sidebar.html, templates/static/products.html
Additional Hebrew copy tweaks
1. In `templates/_sidebar.html` and `templates/static/products.html` adding the ה
- In footer, left as מוצרים intentionally
=> Products Page: Fix Hebrew Copy

helm-chart/sefaria-project/values.yaml
=> docs(linker): add comment to English model

static/js/NavSidebar.jsx, static/js/sheets/SheetsTopics.jsx
We had changed a directory name from `shared` to `common` but forgot to change the code referencing the directory.
=> chore: changed directory from shared to common but forgot to change code

static/js/TopicPage.jsx
This PR prevents loading of filter icon and language icon If author-works-on-sefaria is selected![image](https://github.com/user-attachments/assets/93d4dfc1-09c3-4795-a4ed-81e2e611d96b)
=> Prevent loading of filter icon and language icon when tab 'author-works-on-sefaria' is selected

static/js/ReaderPanel.jsx, static/js/TopicLandingPage/TopicsLandingPage.jsx
=> feat(topics): basic topic landing page

helm-chart/sefaria-project/templates/rollout/task.yaml
=> feat: add slack url var to tasks pod

helm-chart/sefaria-project/templates/rollout/web.yaml
=> fix: move slack env declaration out of otel logic

sefaria/views.py
Fix bug causing topics not to load sources
Revert `int` conversion in `bulktext_api`
=> Fix topics bug

helm-chart/sefaria-project/templates/rollout/web.yaml
Increase gunicorn timeout as a patch to deal with timeout issues from moving app init to wsgi.py
=> fix(helm): increase gunicorn timeout

helm-chart/sefaria-project/templates/rollout/task.yaml
This PR is a hotfix for the helm upgrade error in the task.yaml rollout file 
Fixes curly braces spacing
=> Fix syntax error in rollout file

helm-chart/sefaria-project/templates/configmap/gunicorn.yaml, reader/management/commands/runserver.py, reader/startup.py, reader/views.py, sefaria/wsgi.py
=> fix(helm): move library init code to gunicorn start hook.

static/js/StaticPages.jsx
https://github.com/Sefaria/Sefaria-Project/pull/2128 was missing the other link change in this one.
=> Update additional link for Sefaria's 990 Form for 2023

.github/workflows/weekly.yaml
=> fix: build mongo for arm too

.github/workflows/weekly.yaml
=> feat: add action to free space on the runner

.github/workflows/weekly.yaml, build/standalone-db/buildkit.toml
=> fix: reduce parallelism to avoid port collision

.github/workflows/weekly.yaml
=> fix: correct buildkit config flag

static/js/NavSidebar.jsx, static/js/ReaderPanel.jsx, static/js/TopicPage.jsx, static/js/TopicsPage.jsx, static/js/analyticsEventTracker.js, static/js/sefaria/sefaria.js
Adds analytics to topic TOC. Also adds field called "link_type" which is a new field for topic TOC.
=> chore(topics): add analytics to topic toc

build/ci/production-values.yaml
Test larger memory and cpu footprint for linker
Helm Chart changes
Linker pods are crashing.  Nooooo.
=> feat: Test larger memory and cpu footprint for linker

build/ci/production-values.yaml
=> fix: reduce linker memory requests to fit in the node

static/js/Header.jsx, static/js/common/DropdownMenu.jsx
This is to resolve the open/close inconsistencies between RTL and modularization dropdown menus
=> Dropdownmenu Merge Resolution with RTL

static/css/s2.css, static/css/static.css, templates/edit_profile.html
Adjusted the `edit profile` page to align with the sheets spec. 
1. `static/css/s2.css` - Create specific class for profile save button, override background color to green. (See notes!) 
2.  `static/css/static.css` - Remove flex to enable vertical layout as per spec. 
3.  `templates/edit_profile.html` - Remove sheets/pinned sheets, shift from twitter to `X` and `YouTube Channel` to `YouTube`. 
See notes on card.
=> [Sheets] Desktop Edit Profile

sefaria/helper/link.py, sefaria/views.py, static/js/ModeratorToolsPanel.jsx
new moderator tools for removing links
- new helper function remove_links_from_csv in link.py
- add option to use this function in links_upload_api, when the request has `'action': 'DELETE'`
- new component for removing links in modtools
=> new moderator tools for removing links

static/js/UserStats.jsx
This PR removes the sheets stats from the Torah Tracker. 
1. `static/js/UserStats.jsx` - Remove all references to sheets, underlying functions, and implementations. 
- A chance we may be incorporating other data where sheets was.
=> Remove sheets from Torah Tracker

static/css/s2.css
This is a minor change to improve the readability of mobile search pages.
=> chore: single panel search results css fix

static/css/s2.css, static/js/TopicLandingPage/TopicLandingNewsletter.jsx, static/js/TopicLandingPage/TopicsLandingPage.jsx, static/js/sefaria/sefaria.js
Adds topic newsletter widget to topic landing page
=> Topic landing newsletter

static/css/s2.css
fix languages and layout in editor
=> fix(editor): fix languages and layout in editor.

static/js/NavSidebar.jsx, static/js/sefaria/sefaria.js
RecentlyViewed needs to normalize refs with encoding and also pass version params
=> Rtl client norm url

static/js/sefaria/sefaria.js
check currVersion?.[key] for old saved versions data (the old data can arrive to currVersion when showing the saved items page).
=> Fix saved text page

static/css/s2.css, static/js/UserProfile.jsx
Small tweaks to UserProfile to adjust for the spec when viewing another user's profile. 
1. `static/css/s2.css` - Force URLs in about to have `roboto` font. Temporarily coloring the button green. 
2. `static/js/UserProfile.jsx` - Rendering the follow button under the name in another user's view. 
1. The 'follow' button is a placeholder for the theme-able button. 
3. The font on the collection details is waiting on theme-ability as well.
=> [Sheets][Desktop] Other User's Profile

static/js/TextColumn.jsx
create TextRange with section ref as key, so it won't re-created when TextColumn is re-rendered.
=> create TextRange with section ref as key

static/js/TextColumn.jsx
=> Rtl client

static/css/s2.css, static/js/ConnectionsPanelHeader.jsx, static/js/ReaderPanel.jsx
Reverts Sefaria/Sefaria-Project#2254
=> Revert "Add language toggle to sidebar in Hebrew UI"

reader/views.py, sefaria/urls.py, static/js/Autocomplete.jsx, static/js/ProfilePic.jsx, static/js/ReaderApp.jsx, static/js/UserProfile.jsx
changes in ReaderApp (router), urls.py and views.py (for redirection cases).
=> feat(profile url): change profile url from 'profile' to 'sheets/profile'.

static/css/s2.css, static/js/RowedWordSalad.jsx, static/js/TopicLandingPage/TopicLandingNewsletter.jsx, static/js/TopicLandingPage/TopicLandingSearch.jsx, static/js/TopicLandingPage/TopicSalad.jsx, static/js/TopicLandingPage/TopicsLandingPage.jsx
imlementation of the mobile-web verison of the topic landing page.
for most components, the changes are only in css, whereas for the TopicSalad, a new component was introduced (RowedWordSalad) to be rendered by the topicSalad for mobile web 
=> Topic landing mobile web

static/css/s2.css
fix css of topic of fortune cards to make them flexible depending on screen width
=> Topics of fortune flexible box

static/css/s2.css, static/js/TextColumnBanner.jsx
This is a small accessibility fix for the TextColumnBannerButton component.  This allows you to tab to the button and press enter.
I added href "#", role "button", and tabIndex "0" to get it working.
=> chore: small accessibility fix for go to TextColumnBannerButton button

node/server.js
We had been silently dropping errors in Node SSR.  Here we aim to catch those.
=> feat: Catch and log errors in rendering in Node

reader/views.py
Sheets multipanel mode doesn't exist in modularization.
In our code that handles multipanel requests, we had the option for sheets, so I removed those lines.
=> chore: sheets can no longer appear in multipanel mode

static/css/s2.css, static/js/NotificationsPanel.jsx
Setting up the wiring for an empty notifications page. 
1. `static/css/s2.css` - Classes for empty notifications page
2. `static/js/NotificationsPanel.jsx` - Logic and component for empty page
=> [Sheets][Desktop] Empty Notifications Page

e2e-tests/tests/interface-language-is-sticky.spec.ts, e2e-tests/tests/reader.spec.ts, e2e-tests/utils.ts
=> fix(Tests): fix broken e2e tests

static/js/TopicLandingPage/TopicLandingNewsletter.jsx, static/js/sefaria/sefaria.js
The newsletter subscription now includes mailing lists.
Added a function to get the right mailing lists based on language.
`TopicLandingNewsletter.jsx` → Now fetches mailing lists before subscribing.
`sefaria.js` → Added getTopicLandingNewsletterLists() function.
=> Add mailing lists to newsletter subscription

static/css/s2.css, static/js/TopicLandingPage/TopicLandingSearch.jsx
For search suggestions, the style should match that of the global search suggestions.
=> Tweak style of search suggestions

django_topics/admin.py, django_topics/models/topic.py, django_topics/models/topic_cache.py, reader/startup.py, reader/views.py, requirements.txt, sefaria/model/autospell.py, sefaria/model/topic.py, static/js/TopicLandingPage/RandomTopicCardWithDescriptionRow.jsx, static/js/sefaria/sefaria.js
change pools chace to use pandas dataframe, to support querying pools by topic description
=> Topics pd dataframe

.github/workflows/integration-testing.yaml
=> ci: update github actions versions

static/css/s2.css
=> Polish multi cards for topic landing

.releaserc
=> feat: beta prerelease channel

node/server.js, reader/views.py
Reverts Sefaria/Sefaria-Project#2333
=> Revert "Update redis on restart with node data"

static/css/s2.css, static/js/ConnectionsPanel.jsx, static/js/GuideBox.jsx
=> feat: Move Avot guide button down, make it more prominent

.github/workflows/integration-setup.yaml
=> ci: add common cauldron db setup

e2e-tests/tests/topics.spec.ts, e2e-tests/tests/translation-version-name-appears-in-title.spec.ts
No tests are failing locally after these minor changes.
=> Chore/sc 32547/fix currently failing playwright tests

sefaria/model/passage.py
This PR enhances the Passage model by allowing the "passage" type in validation, facilitating the ingestion of Tanakh stories into the passages collection. Additionally, it adds "source" to the list of optional attributes, improving metadata flexibility.
=> Data Model Changes to Enable Ingesting Tanakh Stories into Passages Collection

static/js/TopicPage.jsx
Remove "Related Sheets" link in sheets module.
=> chore: remove LinkToSheetsSearchComponent

static/css/s2.css, static/js/TopicLandingPage/TopicSalad.jsx
better loading expereice for topic salat
=> prevent layout shift by setting min-height for truncated text

static/js/Header.jsx
Adjusting the logged out secondary nav for header logic
Conditionally rendering menu options based on the module prop. 
See the todo comment- hardcoded module will need to be replaced.
=> [Mobile][Sheets] Secondary nav logged out

static/js/TopicLandingPage/TopicLandingSeasonal.jsx, static/js/sefaria/util.js
This pull request includes changes to the `TopicLandingSeasonal.jsx` and `util.js` files to handle date manipulation in a time zone agnostic manner. The most important changes involve the addition of a utility function and its integration into the seasonal topic display logic.
Date handling improvements:
* [`static/js/TopicLandingPage/TopicLandingSeasonal.jsx`](diffhunk://#diff-55188ddbfee11875da1d47ed36053d762b86a8cd5b48dbbe0fcaf4dd8cc1ba23R6): Imported the `Util` module to use its new date handling function.
* [`static/js/TopicLandingPage/TopicLandingSeasonal.jsx`](diffhunk://#diff-55188ddbfee11875da1d47ed36053d762b86a8cd5b48dbbe0fcaf4dd8cc1ba23L39-R41): Updated the `useSeasonalTopic` function to use `Util.createTimeZoneAgnosticDate` for `displayStartDate` and `displayEndDate` to ensure …
=> Fix false display date

docs/openAPI.json
=> Fixed typos on openAPI.json until ~line 4865

static/js/sefaria/sefaria.js
Use encodeURIComponent on title for encoding question marks.
Adds encodeURIComponent in sefaria.getIndexDetails
=> encodeURIComponent for index API

.github/workflows/production-deploy.yaml
=> fix: correct version of docker login action

helm-chart/sefaria/templates/ingress.yaml, helm-chart/sefaria/values.yaml
=> feat: add sheets subdomain handling

helm-chart/sefaria/templates/ingress.yaml
=> feat: additional redirect and passthrough behaviours for sheets ingress

static/js/Editor.jsx
=> Editor Data Loss - "Text Title" element is lost when opening in new editor

static/js/Editor.jsx
=> fix(editor): always flatten lists

static/js/Editor.jsx
=> fix(editor): strip HTML and convert line breaks in title

static/js/StaticPages.jsx
This updates the copy for the page
Besides copy updates:
* Code was refactored to show the same English content in the Hebrew interface. The page was missing content when the Hebrew interface language was selected
* Styling was added to show the English content in the Hebrew interface correctly
=> Word By Word Page Updates for 2025

static/js/ConnectionsPanel.jsx
Removes jsx for sharing settings from ShareBox in ConnectionsPanel.jsx.
=> Remove share settings from new editor.

reader/views.py
This adds the PDF for the 2024 Impact Report and updates the link.
=> Update file and link for 2024 Impact Report

static/js/AddToSourceSheet.jsx, static/js/common/Button.jsx
We want the "Add to Sheet" button in the library module to appear "sheets" green.  To do this, we can add the 'activeModule' prop to the Button component to override data-active-module of the body element.
=> Feature/sc 26690/update add to sheets button color

static/css/s2.css
Minor CSS change to fix menus display, but first merge https://github.com/Sefaria/Sefaria-Project/pull/2442 before this PR.
=> Feature/sc 32978/css fixes on dropdown menus in modularization

build/ci/production-values.yaml, helm-chart/sefaria/templates/rollout/nodejs.yaml, helm-chart/sefaria/values.yaml
=> fix: configure heap size in nodejs deployment

static/js/sefaria/sefaria.js, static/js/sefaria/strings.js
=> Feature/sc 32313/adding iso code for romanian

static/css/s2.css
CSS changes for long profile descriptions.
=> chore: line clamping

build/ci/production-values.yaml
This reverts commit ea4e9879bec2ad6000fc283018a1aa6b463c0166.
The added memory degraded performance. 
=> Revert "chore: Update node memory requirements"

requirements.txt
=> chore: PyMongo upgrade

requirements.txt
Reverts Sefaria/Sefaria-Project#2466
=> Revert "chore: PyMongo upgrade"

sefaria/helper/normalization.py, sefaria/model/lexicon.py, static/css/common.css
This reverts commit 97a68fd71f812dada96320c1cc9f02a66a4bb620, reversing changes made to cd9ae8581b0041989a6055444430cba25a2aa5a8.
=> Revert "Merge pull request #2290 from Sefaria/krupnik"

sefaria/views.py
Merges master into modularization main
=> Update mod main

static/js/sefaria/sefaria.js
Syntax fix: `en` -> `primaryTitle.en`
=> chore: syntax fix

static/js/Editor.jsx
Enables source highlighting in the sheets editor.  
1. The main change was simply moving HighlightButton -- which handles color highlighting -- so that it always displays in the HoverMenu.
2.  SheetSources are displayed with the component BoxedSheetElement.  I changed the 'onClick' function for BoxedSheetElements so that the user can click on 'hoverButtons' (any FormatButtons (i.e. bold, italics, underline) or HighlightButtons) without it triggering an 'onClick' for the BoxedSheetElement itself.
3.  I changed the HighlightButton component, which allows for color highlighting.  Clicking on the color buttons is now triggered by "onMouseDown" instead of "onClick" because this helps preserve editor focus and prevents unintended blur.
4. I made some changes for readability's sake.  The lines ` …
=> Feature/sc 32331/ 8h max support coloring highlighting of

static/js/Header.jsx, static/js/ReaderApp.jsx, static/js/TopicsLaunchBanner.jsx, static/js/TopicsLaunchBannerGraphics.jsx, static/js/TopicsLaunchBannerMobileGraphics.jsx, templates/base.html
Reverts Sefaria/Sefaria-Project#2512
After second thoughts, MarCom decided to not have the topics launch banner up at the current time
=> Revert "Bring back Topics Launch Banner"

README.mkd
=> fix: Jiggle the handle

.gitignore, e2e-tests/README.md
A readme file explaining how to create tests and how to run them.
There is a section of places that need to be fixed to match this new standard.
One we do those fixes hopefully we can start to improve some of the standards.
=> Playwright infra readme

.github/workflows/weekly.yaml, README.mkd, e2e-tests/tests/banner.spec.ts, helm-chart/sefaria/templates/configmap/nginx.yaml, sefaria/helper/normalization.py, sefaria/helper/schema.py, sefaria/model/lexicon.py, sefaria/model/linker/ref_part.py, sefaria/model/tests/library_test.py, sefaria/model/text.py, sefaria/system/middleware.py, static/css/common.css, static/css/fonts.css, static/css/s2.css, static/js/Editor.jsx, static/js/HeaderAutocomplete.jsx, static/js/Misc.jsx, static/js/sefaria/sheetsUtils.js, templates/base.html, templates/static/annualreport.html
Merges master into modularization main
=> master into mod main

static/js/sheets/SheetsHomePage.jsx
=> chore: remove footer

build/ci/production-values.yaml
=> fix(linker): increase linker ram

build/linker/Dockerfile
=> install-cupy

.github/workflows/mongo-container.yaml
=> ci: make mongo build a nightly occurrence

static/css/s2.css, static/js/Misc.jsx
Just CSS fixes for the language toggle when logged out
=> Bug/sc 35223/alignment in globe icon site language

static/js/Header.jsx
New tab logic was broken.  If in sheets module, a link to the sheets module should not open a new tab.
=> chore: add openNewTab check

sefaria/model/linker/ne_span.py
=> fix(spacy): conditionally set TOKENIZER based on ENABLE_LINKER

sefaria/model/linker/named_entity_recognizer.py
=> decouple-spacy

helm-chart/sefaria/templates/configmap/local-settings-file.yaml, helm-chart/sefaria/templates/rollout/linker.yaml, helm-chart/sefaria/values.yaml
=> fix: correct linker manifests for NER

static/css/s2.css
Got the dropdown to work.
Added `position: relative;`
I tested it in EN and HE. Also tested in sheets.
=> Fixed the search dropdown possitioning

sefaria/urls.py, static/js/ReaderApp.jsx, static/js/sefaria/sefaria.js, static/js/sefaria/util.js
In sheets module, language change causes 404.
(1) Fixed a routing bug by adding the function Sefaria.isSefariaURL.
(2) Fixed the language 404 bug by modifying urls.py
(3) Moved a function from ReaderApp.jsx into util.js where it fits better.
=> Bug/sc 36323/sheets changing language causes 404

static/css/s2.css, static/css/themes/library-theme.css, static/css/themes/sheets-theme.css, static/js/NavSidebar.jsx
=> Bug/sc 36100/subs cauldron logging in from library module

requirements.txt
=> fix: Prep for Aug 31 start of 929 cycle

helm-chart/sefaria/conf/nginx.template.conf.tpl
=> fix: use correct capture group in redirect logic

static/js/Editor.jsx
=> Fix typo in serialization condiiton

static/js/sefaria/strings.js, static/js/sheets/SheetsHomePage.jsx, static/js/sheets/SheetsHomePageTopicsTOC.jsx
I updated 5 strings in the voices landing page.
Currently there was no Hebrew support so I added the string to `strings.js` and used `Sefaria._()`
Two of the strings existed in `strings.js` so I used them as is.
I checked the En and He work.
=> Updates 5 strings and added hebrew support

static/js/TopicPage.jsx
Removed the Related Sheets section from the topic sidebar.
I removed the component and the call to it.
Note, I don't have topic data on my local so I couldn't tests this.
I will test it after merge before I mark the task as Done
=> Removed the Related Sheets section from the topic sidebar

static/js/sefaria/strings.js, static/js/sheets/SheetsHomePage.jsx
Removed an unneeded import
Renamed section in Strings.py to be generally for landing pages and moved three strings from sheets to that section
=> Fix for the strings import and order

static/css/Header.css, static/js/Header.jsx, static/js/common/ModuleSwitcherTooltip.jsx
Sub Branch to implement mobile view support
include ref both from mobile and non-mobile view targets, and decided the relevant based on the multiPanel prop.
Its an inner branch and no so relevant to go through it by itself. please merge it and review them altogether
=> ModuleSwitcher with mobile support

sefaria/model/linker/tests/linker_test.py
=> test(linker): add  test cases for "Guide for the Perplexed" references

sourcesheets/views.py, static/js/UserProfile.jsx, static/js/sefaria/sefaria.js
Update the data fetching affect in SheetsList to trigger on refreshData - which was already being changed when a sheet was deleted.
Changed the request for sheets to be post and not get - as the backend expects
Fixed `class` to be `className` in SheetsList - Removing a console warning
=> Fix deleting of sheets not updating component in user profile

helm-chart/sefaria/templates/_helpers.tpl, helm-chart/sefaria/templates/configmap/local-settings.yaml, helm-chart/sefaria/values.yaml
The issues are from the original PR - [Here](https://github.com/Sefaria/Sefaria-Project/pull/2671#pullrequestreview-3223110594)
I added helpers to generate the domains according to the environment name in order to make exceptions for staging env.
=> Fix Domain Handling issues

static/css/s2.css, static/js/ConnectionsPanel.jsx
Added a secondary option for ToolsButton (Buttons in the side button)
Added a 'open in new tab' icon for the Sheets button
Set the icon button to 14px
Validating we get an altText if an icon is given
=> Bug/sc 36292/sheets link in resources panel of library

sefaria/model/linker/tests/linker_test.py, sefaria/pagesheetrank.py, static/js/ContentText.jsx, static/js/Editor.jsx, static/js/GuideOverlay.jsx, static/js/Header.jsx, static/js/HeaderAutocomplete.jsx
Merges master into modularization-main and add two lines to fix broken links in the mobile header in Header.jsx
=> Bug/sc 37281/mobile web library voices hamburger menu all

static/js/Misc.jsx
=> Mod main merge master
