- static/js/hebrew.js
- static/js/test/test.js
I've ported the hebrew.py code to Javascript in hebrew.js, and also added testing for it using Jasmine.
Not quite sure where the Javascript should go, so I put it in the Sefaria-Project/static/js folder, and the tests folder for js under that as well.
The numbering conventions, etc. are all the same as in the Python.
> Adding hebrew.js and tests

- static/js/sheets.js
The previous behavior was causing errors on production and preventing
any changes to older source texts.
> Source Sheet: Autosave layout change only on 'OK' button

- README.mkd
The link on the current README to the exported data set points to a repo that's no longer there. Updating that link to point to `Sefaria/Sefaria-Project` instead.
> Update link to exported data

- sheets/views.py
Noticed this as I was working on sheets/views.py. Not sure what the exact implications of removing this snippet of code would be, but I noticed it is long past the removal date stated in the comment regarding it. Should the code be removed? Should the comment be updated to reflect its more permanent nature now? I believe @rneiss was the person who added it, so maybe it would be good for him to weigh-in on this.
> remove temp code for backend migration from subsources

- static/css/base.css
Fix typos of font names in /static/css/base.css. `Ariel` --> `Arial` and `san-serif` --> `sans-serif`.
> Fix typos of font names in /static/css/base.css.

- static/css/sheets.css
- static/js/sheets.js
- templates/s2_sheets.html
I decided to take a stab at this issue tonight. My solution was to upload the image to Imgur using the [Imgur API](https://api.imgur.com/) and then, insert the direct link to the image that the API returns into [`inlineAddMediaInput`](https://github.com/Sefaria/Sefaria-Project/blob/master/templates/s2_sheets.html#L358) and trigger a click event on its respective `.button` using jQuery. I'll admit, it's a little bit hacky, but it was working great on JPGs, PNGs, and GIFs when I manually tested it. I would recommend cleaning up the CSS a little bit though. I was having some difficulty styling the `input[type=file]`.
> Closes #233. Upload locally stored photos to Source Sheet

- manage.py
- sefaria/export.py
There's two CTLK export formats that they asked for:
1) cltk-full - convert to cltk format (no arrays, instead use dictionaries with numbered keys) and keep the full structure 
2) cltk-flat - convert to cltk format but flatten to deal with complex text structures that are too complicated for them. The keys are paths to the leaf nodes.
> Added CLTK export format

- sefaria/model/text.py
in a case where the number of segments doesn't match the number of Refs
> added check in text_index_map()

- static/css/reader.css
- templates/edit_text.html
Use label elements instead of plain spans on the "Original Translation"/"Copied Text" options, so that the user can click anywhere on the option instead of just specifically on the radio.
> Use labels on edit_text, for easier selecting

- sefaria/helper/schema.py
- sefaria/model/text.py
Ref.all_subrefs returns empty list if passed a reference to a location beyond the end of the text
migrate_to_complex_structure: gracefull fail if Ref can't instantiate; prevent loss of data when creating the new index
> bug fiexes in Ref.all_subrefs and migrate_to_complex_structure

- README.mkd
1. Fedora now uses `dnf` instead of `yum`.
2. The relevant package is now called `python2-devel`.
> Updated Fedora instructions

- sefaria/model/schema.py
To prevent people from trying to add new indices to the Sefaria library that contain titles of Parashot not using sharedTitles in the future, I added a checker to the validate function that iterates through the indices' nodes' titles and raises an error if any of the titles are Parashot that aren't using sharedTitles.
> Added parashot sharedTitle checker to validate() (and fixed bug)

- README.mkd
Motivation:
Leaving the default reCAPTCHA test keys produces an error. This commit
explains the cause of the error and suggests solutions.
Signed-off-by: Dimid Duchovny <dimidd@gmail.com>
> Update README with reCAPTCHA keys instructions

- static/css/sheets.css
Fixes #487, using recommended fix from @blockspeiser in #490.
This branch updates the `z-index` of `#inlineTextPreview` to be 19, one less than the `z-index` of the `#textBrowser`.
All comments welcome.
> Setting #inlineTextPreview z-index to be one less than #textBrowser

- sefaria/sheets.py
Added code to get a new sheet id when a second new sheet grabbed the same id. The issue will only come up if the sheet "id" index is set to unique (right now it's not).
This method involves an "infinite loop" so I just wanted to get another pair of eyes here. Also, Russel, I changed some code in rebuild_sheet_nodes that allows for a sheet not to have an id when this method is run. The only usage of sheet ids in this method is for printing error messages, so I imagine this not to be a critical issue. But I'm bringing your attention to this change nonetheless.
I've tested this locally. The development django server does allow for parallel processing of requests, so this race condition can come up under heavy load. I've confirmed that on occasion, a duplicate id will get created. If the id …
> resolve sheets race condition

- reader/views.py
Discussions:
- https://groups.google.com/forum/?fromgroups#!topic/sefaria-dev/r-MjlKAr8z8
- https://groups.google.com/forum/?fromgroups#!topic/sefaria-dev/P31bOJ0LIcc\
I don't have a local dev environment set up, so I wasn't able to test things, but I tried within a repl to make sure that this was correct. If someone that does have a dev setup could validate, that would be great.
> Add an optional timezone parameter to /api/calendars

- sefaria/model/text.py
This change removes an `if` statement that is always `True` (the `or True` clause causes the result to always be true, even if `not self._spanned_refs` is false.
The rest of the change is simply outdenting the code that was previously nested inside the `if`.
> Cleanup: Inline conditional that is always true

- README.mkd
In my opinion it is a good idea to propose to this contributors that work on macOS systems on which gettext won't run, to add the needed exports to their .bashrc.
> Propose that the gettext path is added to .bashrc

- reader/views.py
the line "retval = _internal_do_delete" may have been retained in the previous merge.
this line causes the API to fail if a Ref was passed as opposed to an ID which would succeed
> removed unnecessary statement internal_do_delete causing bug

- sefaria/system/context_processors.py
This PR fixes the following error when `USE_NODE` is `False` in settings:
```
UnboundLocalError at /
local variable 'lang' referenced before assignment
/www/sefaria/system/context_processors.py in footer_html, line 175
```
> fix footer_html when USE_NODE is False

- package.json
When attempting to set up Sefaria on Windows 10, I encountered the following problem when running `npm run setup`:
C:\Users\LENOVO\Documents\Sefaria-Project>npm run setup
```
> sefaria-web@1.0.0 setup C:\Users\LENOVO\Documents\Sefaria-Project
> npm install -g nodemon; npm install -g babel-cli; npm install -g forever
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "nodemon;": Tags may not have any characters that encodeURIComponent encodes.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2021-04-22T18_51_24_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sefaria-web@1.0.0 setup: `npm install -g nodemon; npm install -g babel-cli; npm install -g forever`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed …
```
> `npm run setup` now works on Windows

- sefaria/model/user_profile.py
- sefaria/views.py
Removed references to missing (and unused) PARTNER_GROUP_EMAIL_PATTERN_LOOKUP_FILE which were causing failures when running 'python manage.py runserver'
When running `python manage.py runserver` I encountered the following errors:
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000253496F29D8>
Traceback (most recent call last):
File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
fn(*args, **kwargs)
File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\commands\runserver.py", line 124, in inner_run
self.check(display_num_errors=True)
File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\m …
```
> 'python manage.py runserver' now working again

- README.mkd
As documented [here](https://docs.mongodb.com/database-tools/mongorestore/), from MongoDB 4.4 the database tools (including mongorestore) are versioned and installed separately from the MongoDB server, making their installation a necessary step for the import.
Also, since the import is slightly lengthier on Windows (download file - unzip *twice* - go to folder above dump/sefaria, run mongorestore there by adding the folder to path OR specifying the exact exe file location) I think it could be helpful to future Windows devs to state that. I feel that there are a lot of steps here that are assumed or glossed over, which can make it difficult for more junior devs to get started with it.
> Added 'download MongoDB Database tools' to readme

- sefaria/client/wrapper.py
When you have references that span multiple pages, Sefaria attempts to connect the text in the pages together to a single list.
It goes over each page (wrapper.py:215, `for com_oref in con_orefs`) and for each tries to add it to a list.
For the first item in the list (which is usually all you have) it just uses that string (wrapper.py:259, `com[attr] = res`)
However on the SECOND one, it attempts to make a list that will include both.
:262, `com[attr] = [com[attr]]` works fine. However :263, `com[attr] += res` treats the res (which can be a single line of text) AS A LIST, and therefore adds all the elements of the list to the other list... since it's a string, that means the individual chars...
The solution is to check if it's a string or not.
However, I think the real source of the …
> Resolved #541 - multi-page commentary references no longer split into individual letters at /api/texts

- static/js/ReaderNavigationCategoryMenu.jsx
Indexes appea as 'Kifshutah on {masechet}'.
This is a patch for it, so it will appear just with the masechet like other commentaries.
> Tosefta Kifshutah view in TOC

- sefaria/model/text.py
Fix this issue. when `make`-ing `doc`
```
/home/uri/git/Sefaria-Project/sefaria/model/text.py:docstring of sefaria.model.text.Ref.is_segment_level:3: WARNING: Unexpected indentation.
```
See #646.
> fix a doc build indentation issue

- static/css/s2.css
The 'copy link' button in the 'share' menu was jumping around when clicked, which then meant that the link wasn't actually getting copied because the mouse wasn't on the button when it was released.
To get to the button I'm referring to: Open Genesis, click a verse, scroll down in the sidebar to "share," click the copy link button next to the text box.
> Fix 'copy link' button in share menu

- static/css/s2.css
- static/js/Editor.jsx
- static/js/Misc.jsx
- static/js/Sheet.jsx
- static/js/UserProfile.jsx
https://trello.com/c/4TcpUVJm/12-refactor-autocompleter-to-be-generic-enough-to-be-used-here
Major changes
- Refactor Autocompleter to take functions for determining when to show various components of autocompleter (autocomplete results, helper/address completion text, add source button, etc).
- Pull extra results from API then filter/pare down (as opposed to only pulling 5 results)
- Update Editor.jsx to use refactored autocompleter
- Now sending book/corpus to schedules API as separate key/value
Concerns:
- Is this accessible? 
- Too many inline functions in BookCorpusAutocompleter to be readable (lines 563-569)
- Are there edge case bugs I did not catch?
- Original design had startRef/endRef, are we going to use these ever or should I just get rid of them for good?
> Learning schedules autocompleter

- sefaria/model/text.py
`<sup class='endFootnote'>-b</sup>` will now get stripped but 
`<sup>-b</sup>` will not get stripped
Therefore, we will need a Content Quality card that converts the data's sup tags
> Mobileftnotes

- static/js/UserProfile.jsx
https://trello.com/c/RugTMPFn/19-schedule-list-doesnt-update-on-addition-of-new-schedule
> Force schedules list to refresh when a new schedule is created

- .github/workflows/continuous.yaml
Failed and stale jobs continue to live in the dev cluster, remove the job definition once the test has been executed
> ci: cleanup pytest pods once they have finished running

- static/js/ConnectionsPanel.jsx
https://trello.com/c/vUB1Rul3/376-in-new-editor-when-adding-a-connection-from-the-sidebar-the-source-gets-added-instead-of-the-connection-see-video
> Bugfix - 'add to sheet' for sheet connection adds sheet source instead of connection

- sefaria/model/text.py
- static/js/ReaderPanel.jsx
- static/js/TextRange.jsx
Version links now behave as expected, although a script on prod needs to be run.  One thing though: I'm not sure about the change I made to ReaderPanel, where I passed `replace` to showBaseText.  It seems like it should be passed but perhaps there was a reason why we didn't want to pass it?
> Version links

- helm-chart/Chart.yaml
> fix: bump helm-chart version for backup logic

- helm-chart/templates/jobs/mongo-restore.yaml
- helm-chart/values.yaml
I'm leaving out the selective destroy for now - I think the idea we discussed where cauldrons who's data should persist should rather be backed up and then that can be used as the base for a new restore at a later point.  This will still help with mongo-in-a-can setups, which would not need to restore, as well as migrating old cauldrons to reuse their existing DBs.  For the latter cauldron creation would probably need to be manual, unless there's a feeling disabling restore would be something that should be added to the cauldron creation process?
> feat: allow restore to be disabled in helm chart

- static/js/sefaria/search.js
Added a line to remove slashes from Hebrew refs from Dicta, and to reformat in Sefaria Ref style. Returned search results now look like this:
> Reformat Hebrew refs

- static/js/TextRange.jsx
Fixing this bug https://trello.com/c/FtWbxt9b/471-double-clicking-word-to-get-definition-when-sidebar-is-closed-causes-jumping-wrong-word-selected
> Double click bug

- static/js/TextColumn.jsx
- static/js/TextRange.jsx
Moved the logic from TextRange to TextColumn for onclick and doubleclick to avoid second click firing in the empty space on the margins.
> Fix for doubleclick on TextRange.

- helm-chart/sefaria-project/templates/rollout/linker.yaml
`value: '{"he":"gs://sefaria-ml-models/ref_model.tar.gz"}'`
vs
`value: "{"he":"gs://sefaria-ml-models/ref_model.tar.gz"}"`
> fix: correctly encap json string output

- sefaria/system/middleware.py
I spent a while trying to trace down a seemingly unrelated error on a new API I was working on. After a while, I figured out that the error was actually a red herring and the real error was that the URL was hitting a 404. This PR fixes that red herring error.
> fix: 404 pages no longer fail due to missing attrs on request object

- README.mkd
tar -x dump_small.tar.gz
give this error in windows:
tar: Error opening archive: Failed to open '\\.\tape0'
and this error in ubuntu:
tar: Refusing to read archive contents from terminal (missing -f option?)
tar: Error is not recoverable: exiting now
the correct command is 
tar -xf dump_small.tar.gz
with an f after the x
> updated to correct command

- reader/views.py
- static/css/s2.css
- static/js/ReaderApp.jsx
- static/js/TranslationsPage.jsx
Hi Russel! This PR adds the following ux improvements to language pages (details here: https://trello.com/c/GuzEI5pl/2786-language-page-improvements)
- When users click a text from a language list, their content language is switched to bilingual for that session only
- Prioritized texts should show up at the top of category, not under uncategorized
> Translations ux updates

- requirements.txt
This fixes an issue with ipython autocompletion in the command line, after a version of ipython became incompatible with one of its dependencies, jedi.
Ipython is still not at latest because of python changes required
> feat (python-dependencies): Update ipython and jedi to newer versions

- .github/workflows/production-deploy.yaml
@EliezerIsrael We will need IMAGE_NAME secret set with the appropriate values for each project in the corresponding repos before this merges, or deploy will break
> ci(deploy): abstract out image names for contextus fork

- reader/templatetags/sefaria_tags.py
- reader/tests.py
- reader/views.py
Move all imports to toplevel in Sefaria ./reader.
This reduces lines and duplicated imports as well as code readability overall.
This is also part of the PEP8 Standard (C0415)
> Move all import to toplevel in ./reader

- static/js/ReaderApp.jsx
- static/js/TextList.jsx
Fixes two issues
1. Encodes URI in history so that ReaderApp can properly compare old URL to new URL (one was not URL encoded before so they were considered different)
2. Only preload text for TextList when filter changes
Fixes this card: https://trello.com/c/RMjyHww2/2820-connections-panel-flashes-reload-on-minor-scrolling-not-past-segment
> Bugweek connections panel flashes

- static/js/NavSidebar.jsx
- static/js/SearchSheetResult.jsx
- static/js/TopicsPage.jsx
- static/js/sefaria/strings.js
Addressing the issues on [this](https://trello.com/c/0HHNe8P0/2629-hebrew-language-issues-in-search) card. 
1. Topics "about" description appears in English, not Hebrew on the Hebrew side of the site
2. "Create a New Topic" button appears in English, not Hebrew, when logged in on the site. "Edit a Topic" button appears in English, not Hebrew, when logged in on the site. 
3. Ending punctuation on English language sheet titles is mixed up LTR/RTL
> Bugweek hebrew language issues in search

- README.mkd
- sefaria/local_settings_example.py
It was not clear if one needs to create a sqlite database as part of setup, and how that works with Django for the `manage.py` script. These small changes are an attempt to clarify, both in the language of the comments and in the `README` itself.
> Clarification for setup documentation

- templates/base.html
The previous code was generating http links instead of https links, and fb wasn't picking up the appropriate description from the default meta tag.
> fix: Facebook image previews work properly again

- helm-chart/sefaria-project/templates/configmap/varnish-config.yaml
- helm-chart/sefaria-project/templates/rollout/varnish.yaml
implement separate configmaps per release that align varnish with specific web instances for cache sanity as occurred previously
> helm(fix): fix bug in varnish config setup

- .github/workflows/weekly.yaml
- build/standalone-db/Dockerfile
This ended up being a bit more difficult that I originally thought because of some fine grained stuff about how docker build works and what the mongo image does upstream.  Essentially docker is told to ignore anything that ends up in /data/db because it's expected that the container will be connected to some form of persistent volume at that location, because generally DB contents are explicitly not supposed to be in an image.  I worked around this by shifting the whole DB to a new location.  There's a couple caveats now though:
If a dev wants to run this image with any funny commandline overrides to mongo (eg hosting it  on a different port), they'll also need to know to point mongo at the new database location.
Devs would need to know they need to take snapshots of the image if they …
> feat: create Dockerfile for standalone development database container

- sefaria/model/topic.py
Update error handling to `InputError` to allow for topic link merges handling bad refs
> Catch errors with bad refs in topic links

- static/js/BookPage.jsx
All the texts I tested had an authors value of an empty array.  However, I've just noticed that many texts are missing an authors field entirely.  This line deals with those texts.
> fix: Index Editor with 0 authors fails

- static/js/ReaderPanel.jsx
- static/js/TextRange.jsx
- static/js/sefaria/sefaria.js
For TextRange this is a basetext, allow redirect to first content ref. 
But for links, don't rewrite the refs.  Thus avoiding cache miss and infinite loop.
> Infinite load commentary fix

- sefaria/model/following.py
- sefaria/model/notification.py
- static/js/NotificationsPanel.jsx
I needed to add `is_already_following` to the notifications api because I need to use this API in mobile and we don't have access to `Sefaria.following` (a global variable of all users following the currently logged in user). Anyway, `Sefaria.following` is bad architecture and it's preferable to get the data from the api directly.
> is_already_following field on notifications api

- static/js/sefaria/sefaria.js
The issue was the same collective name but different books therefore different descriptions. eg Be'er HaGolah. The fix looks for a fullName and gets the description from the correct index. Note: the index must have a shortDescription on the document in mongo.
> fix(sidebar): Fix to sidebar description same index names bug.

- static/js/ReaderApp.jsx
**Resolves** https://trello.com/c/xwL5do14/93-text-copied-from-a-bilingual-torah-presentation-w-fox-translation-and-pasted-into-a-rich-context-is-missing-elements
**Example**
**Context**
Google Docs in Chrome doesn't process pasted html data in the case of span's with classes within div's. The poetry spans are now collapsed to prevent the missing Hebrew text from happening.
> Fix copying/pasting poetry translations into Google Docs in Chrome

- build/web/Dockerfile
We remove the line --use-feature=2020-resolver from the call to pip install since it has become the default dependency resolver and the warning against using it is scheduled to become an error in alter versions of pip.
> ci: Update Dockerfile to remove the deprecated pip command.

- static/css/s2.css
- static/js/TextRange.jsx
I renamed .poetry to .poetry .indentWhenWrap simply for clarity's sake as there are in this PR three different poetic stylings.
> feat(Poetic Formatting): added poetry classes to s2.css

- static/js/ReaderApp.jsx
- static/js/sefaria/util.js
Bug: handleCopyEvent event is only meant to handle copy of HTML elements, when no HTML element is present the copied text is lost.
Fix checks if string is HTML element, and if it isn't we allow the browser to continue as usual
> Bug: fix copy past for non html elements

- sefaria/helper/linker.py
- sefaria/helper/tests/linker_test.py
- sefaria/views.py
- static/js/linker.v3/main.js
Note, since this code changes the signature of `make_find_refs_response` which is cached using django_cache, this will invalidate the entire current linker cache. I don't see a way around this and I don't think it will be a big deal.
> Linker specify version

- sefaria/datatype/jagged_array.py
- sefaria/datatype/tests/jagged_array_test.py
Solves an issue with trim whitespace that was causing bad data to be saved to our DB. See [here](https://app.shortcut.com/sefaria/story/551/skipping-problem-while-scrolling-on-reader). Need to run a script on production to clean out this bad data once this is launched.
> Bug/sc 551/skipping problem while scrolling on reader

- sefaria/model/category.py
The error below is cause by categories that are not in the system. This PR should correct that by failing gracefully and giving us a warning
> fix(startup): fail gracefully when loading categories

- static/js/SearchResultList.jsx
https://app.shortcut.com/sefaria/story/284/book-description-on-he-ui-appear-in-en-in-search
> fix(search): show short description when long is missing.

- static/css/s2.css
removed a css line applies to all the sheet. it seems that hebrew text has their own css for rtl.
https://app.shortcut.com/sefaria/story/19196/rtl-broken-on-sheets-when-in-hebrew
> fix(sheets): hebrew interface english text to be ltr.

- .github/workflows/production-deploy.yaml
This is only a temporary measure until we get the pieline for updating the chart version sorted. Generally one should not make changes like these directly.
> ci: Temp manual bump of default chart version.

- static/js/sefaria/search.js
this should fix this bug - https://app.shortcut.com/sefaria/story/866/search-bugs-tanakh-search-result-eliminates-all-other-results-once-marked-off-all-other-results-load-properly-and-other-issues .
also - all the logics that have been removed seems to be useless and redundant.
> fix(search): remove all the pivot logics from mergeQueries.

- static/css/s2.css
https://app.shortcut.com/sefaria/story/587/navigation-page-sidebars-stay-in-center-of-page-on-large-screens#activity-19515
> Layout width

- static/js/ContentText.jsx
- static/js/sefaria/sefaria.js
The function Sefaria.isImage() would decide if an image takes up the full segment by simply checking if an image tag existed in the text. We now distinguish between the full segment image case and an inline image case by making the regex more specific.
> fix(reader): Fix bug that hid inline text when there was a base64 image

- static/js/Editor.jsx
When Gods name is used in freetext and fools our Divine name replacer into action, it attempts to replace it with undefined, while it is difficult to truly define God, as only Moses was permitted to say ויציב ונכון וקיים וישר ונאמן ואהוב וחביב ונחמד ונעים - still, this causes an error and white-screens the editor app. I have added a check for the prop changing the Devine name
> fix(editor): check for divine name replacement before replacing

- sefaria/helper/normalization.py
- sefaria/helper/tests/normalization_tests.py
Fix various off-by-one errors in normalization code. Refactor some of the code to be simpler / faster so that it was easier to reason about while debugging. Modify tests that were incorrectly accounting for off-by-one errors.
> Normalization fixes

- static/js/Misc.jsx
- static/js/context.js
* Resolves https://app.shortcut.com/sefaria/story/20508/allow-background-color-as-an-option-for-banners
* Depends on https://github.com/Sefaria/Sefaria-Project/pull/1606 and https://github.com/Sefaria/Sefaria-Strapi/commit/4cd140e7f463941dcb566d26d60d6f6c23770502
* bannerBackgroundColor attribute was added to the GraphQL query
* Check if the optional background color is not null and use it. Otherwise, the background color for a banner will default to what's already included in the CSS file
* bannerBackgroundColor was added to the banner content type for the Strapi server
A bug was fixed where there was two close buttons on banners...
> Allow the background color of a banner to be customized in Strapi

- static/js/context.js
A user reported being unable to get rid of the current deployed banner when they closed it out. They continued to see the banner after interacting and making repeated visits to the Sheets Editor page.
The bug occurred in the following scenarios:
* Interacting with a banner (hitting the close button or donate button) and then going to a static page with ReaderApp in header-only mode
* Interacting with a banner and then starting a new session (closing tab or window)
**Discovered problem:** the entry in local storage to mark whether a banner or modal had been interacted with was being cleared on every page load or session even in the usual case where the current banner or modal hadn't changed.
If the current modal or banner is found to be the same as the eligible one returned from Strapi, …
> Banners (and modals) wouldn't go away but now they will

- static/js/Promotions.jsx
This fixes a small typo that left the attribute used for URLs to be undefined
> URLs on buttons in Hebrew Sidebar Ads were missing

- reader/views.py
- static/js/Misc.jsx
- static/js/ReaderApp.jsx
- static/js/ReaderPanel.jsx
- static/js/TopicPage.jsx
Add sort URL param to topic pages.
This will track the sort option on topic pages which can be either "Relevance" or "Chronological".
> Bug/sc 20275/chronological filtering isn t sticky on topics

- sefaria/client/wrapper.py
- sefaria/model/garden.py
- sefaria/model/text.py
We are temporarily setting compDate to 3000 across the site in preparation for running a script that normalizes dates by converting strings into lists.  We will then deploy a different branch with code that properly handles compDate as a list
> chore: set years to 3000 ignore compDate

- helm-chart/sefaria-project/templates/configmap/nginx.yaml
- helm-chart/sefaria-project/templates/rollout/nginx.yaml
Story details: https://app.shortcut.com/sefaria/story/19579
This is likely wrong lol. I only tested the redirection part in an example Nginx Docker container on my local. I don't know the correct location or way to reference the secret environment variable used to define `STRAPI_LOCATION`. Since it's only for production, the port shouldn't be necessary.
I integrated Strapi CMS into Sefaria's codebase. It's currently used on the web interface to serve the content for modals, banners, and sidebar ads. The mobile app currently uses static JSON files for that content which the site needs to redeployed every time when a change needs to be made (see [here](https://github.com/Sefaria/Sefaria-Mobile/blob/c05a9566212ba58d1b0ada3b4b1ce2f513fd066b/InterruptingMessage.js#L68)). To remove the last …
> Redirection to Strapi endpoints for mobile app users

- static/js/Misc.jsx
Banners were continuing to show up after the donate/banner button was clicked. Tracking events for banner button clicks and banner closes was also missing. This PR fixes both problems. This assumes that the banner should not be shown again after the button is clicked on a different page load and that it should be closed on the current page when the button is clicked.
> Banners were continuing to show up after interaction

- sefaria/model/text.py
I added this to prevent us from adding compDate and pubDate values that are not lists of integers as someone did recently change compDate and pubDate of two texts to integers seemingly via the API.  (It isn't possible to make this mistake using the admin tool UI so I assume the only possibility is the API).
> fix(Index Save): validate compDate and pubDate are lists of integers

- sefaria/helper/topic.py
- static/js/CategoryEditor.jsx
1.  When merging sources to display in a topic page, any source added by the learning team should be treated separately.  I added checks [here](https://github.com/Sefaria/Sefaria-Project/compare/fix_learning_team_links?expand=1#diff-19364da9061bcb429f3f3c5f63aeab5541e461154bd59e61719b2cd68f631356R173) and [here](https://github.com/Sefaria/Sefaria-Project/compare/fix_learning_team_links?expand=1#diff-19364da9061bcb429f3f3c5f63aeab5541e461154bd59e61719b2cd68f631356R185-R186)
2. I removed the decorator function which was interfering in the merging of two sources where the new one isn't a learning team source.  We wanted to use the source with the smaller expandedRefs but that was not possible because of the decorator.  And it's irrelevant now that learning team links are not merged with …
> Fix learning team links

- static/css/s2.css
A simple property change was made to ensure the navigation menu on mobile web is displayed properly when a banner is displayed.
In collaboration with @yonadavGit :)
> Banners don't jumble up the mobile navigation menu anymore!

- sefaria/model/tests/ref_test.py
- sefaria/model/text.py
- sefaria/model/text_manager.py
If `other` Ref is a whole book, and `self` begins anywhere after first segment, `contains` is trivially false and we can avoid expensive code.
> fix: Performance improvement of Ref.contains

- static/js/sefaria/sefaria.js
This PR addresses https://github.com/Sefaria/Sefaria-Project/issues/1693. 
It flagged the fact that React imports were left over in sefaria.js and created the impression (both to human and machine bundler alike) that sefaria.js is dependent upon React.  
The PR undoes commit https://github.com/Sefaria/Sefaria-Project/pull/1507/commits/1af87886e84b6eafe6ee2f0bd817d7d0c131af4c#diff-2f1b7852161a95e253017883a3aa2a5d372103e32b61cfd95ff57edc7ffaaf43 in PR 
https://github.com/Sefaria/Sefaria-Project/pull/1507/files#diff-2f1b7852161a95e253017883a3aa2a5d372103e32b61cfd95ff57edc7ffaaf43
This is done to ensure that sefaria.js uses vanilla js and does not become dependent on React
> Remove unused React dependencies from sefaria.js

- sefaria/model/timeperiod.py
- sefaria/pagesheetrank.py
this PR should solve this problem in reindex ElasticSearch - https://sefaria.slack.com/archives/C1DAVPYJZ/p1699190830515399
it adds a new function to TimePeriod - determine_year_estimate, and uses it in page ranking rather than using the start attribute which is not a required attribute.
> Period year

- sefaria/model/place.py
Previously, it was possible to accidentally enter "1520" as a birth place as this was the address or postal code of some place somewhere.   Now, we will only accept real places.
> fix(Admin Editors): verify places are real cities

- static/js/Misc.jsx
A bug was introduced in https://github.com/Sefaria/Sefaria-Project/pull/1663 that prevented banners/modals from showing up and the web app from loading if there was only a default English localization and not a Hebrew one. Banners were previously able to be rendered without a Hebrew localization, allowing banners to be targeted towards only English interface users. If a Hebrew localization was not defined, the button URL would cause a null reference error.
> Allow banners/modals to render when there isn't a Hebrew localization

- static/js/Header.jsx
- static/js/sefaria/sefaria.js
"josephus" was setting off an infinite recursion where repairCaseVariant returns "josephus" each time because it is designed to correct refs not topics/categories.  My solution is not call submitSearch if repairCaseVariant returns the same value as the inputted value and avoid the recursion.  I also noticed that topics won't get opened unless the search starts with "#" so I added a check to see if the type is "Topic" or "AuthorTopic".
> fix(Search): josephus doesnt freeze search

- static/css/s2.css
fixed three pixels top padding on both the user and help icon in the desktop web header that should not be there
> chore(HeaderIcons): aligned header buttons

- reader/views.py
- sefaria/system/database.py
This PR addresses the fact that mongo/pymongo does not error out by itself if you attempt to connect to a database on the server the client is connected to. 
This adds functionality that will check the db name's existence on the server first and throw an exception if not, this blocking the website from functioning. 
Also added a clause to the healthz health check, but that will probably never get called because now the code will error way before.
>  Check for db name existence

- reader/views.py
- sefaria/system/database.py
(Duplicate of previous https://github.com/Sefaria/Sefaria-Project/pull/1655 in order to replace it being merged into a discarded branch)
This PR addresses the fact that mongo/pymongo does not error out by itself if you attempt to connect to a database on the server the client is connected to.
This adds functionality that will check the db name's existence on the server first and throw an exception if not, this blocking the website from functioning.
Also added a clause to the healthz health check, but that will probably never get called because now the code will error way before.
> Check for db name existence

- locale/en/LC_MESSAGES/django.po
- locale/he/LC_MESSAGES/django.po
- static/js/NavSidebar.jsx
- static/js/StaticPages.jsx
- static/js/sefaria/strings.js
- templates/static/app.html
- templates/static/aramaic-translation-contest.html
- templates/static/dicta-thanks.html
- templates/static/en/about.html
- templates/static/he/about.html
- templates/static/home.html
- templates/static/jobs.html
- templates/static/mobile.html
Marketing and Communications has requested that "non-profit" be "nonprofit" instead in all visible text captions. All the relevant instances that are publicly visible have been changed. Caveat: I'm not sure if the instances specified in the Django translation strings files are actively used, but I changed them in case they are.
> Change "non-profit" to "nonprofit" in all instances

- static/js/ContentText.jsx
Markdown text currently shows in the sidebar instead of being rendered as markdown.  This is because ContentText never was fully implemented to work with markdown.  ContentText previously received markdown as a prop but did nothing with it.  It now passes it down to ContentSpan which renders markdown appropriately.
> fix(Topics): topics shown in sidebar did not display markdown properly

- static/js/Misc.jsx
- static/js/TopicPage.jsx
We don't want to display links in markdown text in all places on the site, specifically in the topic TOC.  However, we still want other markdown tags to show, such as italics.  Therefore, I added a field to InterfaceText `disallowedMarkdownElements` which is a list of the elements you don't want to show in markdown.  In this case in the change I made in TopicPage.jsx, I pass ['a'] and links do not show up but italics does show up.
> fix(Topics): display without links in the TOC but with links on topic pages

- sefaria/helper/search.py
bug fix:
search in book will return results for any book that starts with the book title you’re in. So searching in “Zohar” should return results for “Zohar Chadash” as well.
> fix(SearchFilters): changed 'path' regex to ignore books which the current book title is their prefix

- helm-chart/sefaria-project/templates/cronjob/reindex-elasticsearch.yaml
It seems a new line was auto-added when files were moved to the "scheduled" folder.
> fix(search): remove newline that was auto-added

- static/js/AdminEditor.jsx
We were using a deprecated property `is_textarea` to determine whether to validate the markdown links in descriptions in Admin Editors.  I added a property `markdown` and changed the check so that it checks that the property `markdown` is True.  I only set this property to true for descriptions and not for any other field in admin editors, such as titles or captions.
> fix(Markdown): markdown in admin editors was not being validated

- static/js/AdminEditor.jsx
In the admin editor, fields set as `type` equal to `textarea` are displayed using HTML textarea elements rather than input elements.  For prompts in the source editor, I had mistakenly set this incorrectly, so that it had a `textarea` property instead of having a `type` property that was set to `textarea`.
> fix(Source Editor): Prompts should be textareas not input elements

- helm-chart/sefaria-project/templates/configmap/nginx.yaml
ES no longer requires this header to be set and it's problematic to set it to application/json because ES has a strange requirement that if Accept is set to "application/vnd.elasticsearch+json; compatible-with=8" (which is sent from our Python ES client) than Content-Type needs to be set to the same thing.
> helm(search): dont set Content-Type header.

- static/js/SearchResultList.jsx
- static/js/sefaria/search.js
- static/js/sefaria/searchTotal.js
This ensures that both Dicta and Sefaria queries are using the same format of SearchTotal.
> fix(search): move encapsulation of SearchTotal to search.js

- sefaria/helper/linker.py
- sefaria/helper/tests/linker_test.py
Passed wrong order of parameters to FindRefsTextOptions. Also, modified test to test this case. Fixes https://github.com/Sefaria/Sefaria-Project/issues/1786
> fix(linker): fix order of parameters

- static/js/Misc.jsx
The bug was that we currently cannot create new categories using the Category Editor.  This is because of this typo corrected below.  `origEnTitle` should be `origEn`, as that is the name of the property in the CategoryEditor component.
> fix(Category Editor): fix typo origEnTitle => origEn

- static/js/sefaria/sefaria.js
[This commit](https://github.com/Sefaria/Sefaria-Project/commit/9f6b71eb) seems to be the cause of the issue. The v3 text API gets sent false as a boolean parameter. Running this through bool and int yields an error because int("false") isn’t valid in Python.
This PR makes sure the client sends 1 or 0 to the server.
> fix(translations): make sure fill_in_missing_segments is either 1 or 0

- static/js/StaticPages.jsx
- templates/static/powered-by.html
* The header and footer were fixed when the interface language is switched to Hebrew.
* Parts of the page were updated to add the new developer email address & link to the portal, and  to adjust some text.
Future considerations
* The static pages that currently only have English and no Hebrew translation need a better method for representation. The approach taken now unnecessarily provides duplicate text. The previous approach of only providing English and changing thestyle classes based on the interface language was broken for this specific page. The header and footer did not work.
* This scenario of showing English when there is no Hebrew translation needs to be considered when this page and other static pages like it are adapted to use a CMS like Strapi.
> Update "Powered By" Page for Developer Portal Release

- sites/sefaria/urls.py
Strategy team requested a new redirect for the upcoming gala as mentioned  [here](https://trello.com/c/n61elxik/537-page-on-sefariaorg-that-leads-to-new-donation-page)
> Add new redirect to donation page for the path '/giving'

- sefaria/model/timeperiod.py
This bug occurs in:
"en": re.sub(r'[()]', '', tp.period_string("en")),
as period_string method is expected to returns a string. By returning None we break the regex code and the topic doesn't load for any topic without a time period (see https://www.sefaria.org.il/topics/tzadok for example)
Bug detected on Sentry:
https://sefaria.sentry.io/issues/4604800087/?project=4505401833684992&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=10
> bug(timeperiod): Return string from LifePeriod class

- sefaria/helper/crm/crm_mediator.py
It seems we forgot to bubble the return value up so that the view can know if the subscription was successful.
> fix(crm): return status of CRM subscribe function.

- build/linker/Dockerfile
The latest upgrade to python 3.9 broke the linker pod. This PR upgrades spacy to the latest version which fixes an issue in a dependency with pydantic.
> Fix pydantic

- build/ci/production-values.yaml
This PR simply disables the setting to run the nationbuilder cronjob
> Disable nationbuilder cronjob temporarily 

- sefaria/model/topic.py
We no longer want slugs to change based on a title change.  The entire `add_title` of topic.py was dedicated to cascading a primary title change to the slug and so I removed this function.  Now, changing the primary title can be done and the slug does not change.
https://app.shortcut.com/sefaria/story/24547/fix-issues-created-by-renaming-topic-titles
> fix(Topics): dont cascade title change to slug

- static/css/s2.css
- static/js/AddToSourceSheet.jsx
- static/js/Header.jsx
- static/js/Misc.jsx
- static/js/Promotions.jsx
- static/js/TextColumnBanner.jsx
- static/js/sefaria/strings.js
This is an ad in the Connections Panel below the "Ad to Sheet" button.  It displays an "Install Now".  The ad displays unless the user has clicked "Install Now" in the past.  Moreover, the first time it renders it calls google analytics and "Install Now" calls google analytics so that we know how many times the button was seen vs. clicked.
> Feature/sc 21757/place a message next to the add to sheet

- docs/openAPI.json
This PR is a suggestion on a fix to supply the v3 Texts API parameter: return_fromat with the correct list of possible values. 
It adds an enum to the schema of that param.
> docs: Correct list of values for api/v3/texts return_format

- reader/views.py
- sites/sefaria/urls.py
- static/js/Footer.jsx
- static/js/StaticPages.jsx
Every year, a new annual impact report is created and links need to be changed in more than one place when the report is ready for the Sefarian world abroad. 
To handle this scenario and minimize the amount of code changes, the path for the annual report will now be `/annualreport` in links instead of `/annualreport/<year>/`. The default path will now refer to the most recent report. However, the ability to refer to specific years by the path will still be allowed and to ensure backwards compatibility with previously given out links as was previously done.
* Footer link to annual report is now `/annualreport`
* Link on _Ways to Give_ page is now `/annualreport`
* The endpoint function for that path now handles both URL patterns `/annualreport` and  `/annualreport/<year>/`
* The function …
> Add reference to 2023 annual report & change URL path to be dynamic

- templates/static/supporters.html
* One entry was in the wrong section
* Another entry had an extra 's'
> Fix mistakes from previous update to Supporters page

- sefaria/search.py
Noticed that my choice to delete the `not` vs adding another `not` turned the function name to be very misleading. This PR is an attempt for a more indicative name.
> fix(search): more indicative function name

- reader/views.py
In the past, topic title changes would cascade to the slug.  Recently, we changed things so that topic title changes would not cascade and change the slug.  This caused the Topic Editor to stop working because it relied on the old way.  I added a line to directly set the slug based on the primary title.
> fix(Topic Editor): couldnt create new topic because slug was empty

- reader/views.py
Bug: When the sidebar is open, the base ref that was clicked to open the sidebar is not always highlighted.
Solution:  Whenever the sidebar is open, some `with=` is present in the sidebar currently presented in the code by the variable `filter.`  Therefore, on the backend when this `filter` is present the backend can create panels with `highlightedRefs` and `showHighlight` already set.  By doing so, when the sidebar is open, the base ref is always highlighted.
A confusing feature of the previously existing implementation is when the sidebar is first opened, `with=all` is represented by a `filter` value of an empty list.  When Rashi is open in the sidebar, `filter = ["Rashi"]` and finally, when the sidebar is not open, `filter` is None.  Therefore, you can have a `filter` value of an empty …
> feat(Reader Panel): Show segment as highlighted whenever the sidebar is open

- sites/sefaria/urls.py
- static/js/StaticPages.jsx
- templates/static/the-sefaria-story.html
There is currently a problem with Classy: when a campaign uses the short URL with "en", it redirects to Classy's main page instead of the campaign page. This is a bug with Classy and not with any of our configurations.
As a temporary workaround until the bug is resolved on Classy's side, links have been changed to point to Sefaria's main campaign donation page.
https://donate.sefaria.org/en redirects to https://classy.org and can't be changed right now
> Temporary fix for donation links

- templates/static/linker.html
This PR just redirects the button that leads to the linker install docs from the old Github location to the developer docs site.
> Change docs url for the linker

- sefaria/model/tests/chunk_test.py
assert "Kiddush" in c.text[0] needs to be assert "KIDDUSH" in c.text[0] in new uppers text paradigm
> fix(test): fix pytest test_complex_with_depth_1

- sefaria/model/user_profile.py
This PR changes the default init of a new UserProfile object and makes it so all new users default to having their profile direct them to the newer of the 2 source sheet editors, something that was previously only enabled for a select group of beta user testers.
> Change default on new users to all use "new" sheet editor

- sefaria/model/tests/text_test.py
Changes to the test:
In test_index_update, 'lengths' can no longer be set.  'addressTypes' can be set when creating a new Index with load_from_dict, and so this succeeds, but 'addressTypes' cannot be changed by merely using load_from_dict, so the attempt to change 'addressTypes' to ["Integer", "Integer"] fails.
> Bug/sc 25982/index editor doesn t work with jerusalem

- docs/openAPI.json
Currently the `Recommended topics` title (called `summary` in the spec) has topics lowercase, as opposed to capitalized. This PR removes the word `API` and shifts to all uppercase to ensure consistency with our other endpoints in the devportal.
> Fix Capitalization 

- static/js/sefaria/sefaria.js
This helps prevent characters like ? in refs from ruining the URL. Example ref that caused problems because of the question mark: `Covenant and Conversation; Numbers; The Wilderness Years, Nasso, What Counts? 28-30`.
> fix(topic pages): encode uri components that go into api/bulktext.

- static/js/Misc.jsx
- static/js/sefaria/strings.js
Alt text for images:
The featured topic image
Use the caption
If there is a limit to length for alt, truncate accordingly
For EN UI, use EN caption or fall back on "Illustrative image"
For HE UI, use HE caption or fall back on " תמונה להמחשה "
> feat(topic page): compute alt text for topic image

- static/css/s2.css
- static/js/Misc.jsx
- static/js/sefaria/strings.js
At the top of the reader is a toolbar including an A/Aleph icon which opens the "Reader Options" control. The task here is to add a fast-acting tooltip which is triggered by hover on the icon.
We have this functionality today right next to the Reader Options icon - the bookmark icon has a fast-acting tooltip and we can simply re-use whatever code powers that.. changing the message of course.
Tooltip EN - Text display options
Tooltip HE - אפשרויות תצוגת טקסט
> Add tooltip to reader options icon

- reader/views.py
- sefaria/helper/topic.py
- static/js/Misc.jsx
- static/js/TopicPage.jsx
This fixes a few issues with inconsistent sorting found by the learning team:
- If a source appears multiple times on the page, editing will prefer the one with the highest curatedPrimacy
- Server-side and client-side relevance sorting are now (hopefully) identical
- Don't filter sources that don't have text in `interfaceLanguage` in the admin reorder view since this doesn't match how sources are sorted in the client-side code.
> Fix topic ordering issues

- static/js/TopicEditor.jsx
This PR simply changes the maximum number of characters for a topic image caption from 150 to 300.
> fix(Topic Editor): allow 300 character captions

- static/js/ReaderApp.jsx
There is currently a consistent history bug in the app that affects navigating the library TOC, using search filters, and the topic TOC.  What can happen is that clicking on a category in the library/topic TOC successfully loads the page it's supposed to, but it does not update in the URL.  Instead, the URL remains "/texts" or "/topics" for example depending on the case.  I noticed that when this bug occurs, in `shouldHistoryUpdate` in ReaderApp.jsx, `history.state` and `this.state` referred to the same object in memory so that `this.state.panels` and `history.state.panels` were also identical objects in memory, which is why `shouldHistoryUpdate` returns false and the URL doesn't get updated properly.  This is ultimately because of two things:
1) in `handlePopState`, we do not clone the …
> fix(History): handlePopState should clone state

- sefaria/model/topic.py
Default inherited from abstract.py mangles Refs with ampersands in them. The new implementation avoids that and instead sanitizes title and prompt which can actually be vectors for attack.
> fix(topics): overwrite RefTopicLink._sanitize.

- static/js/Autocomplete.jsx
- static/js/lib/keyboard.js
This PR fixes synchronicity between virtual keyboard and search bar
> fix(search bar): enable search with input from virtual keyboard

- reader/views.py
In refactoring the way the admin editor client sends requests, this view started to break because it's using an older standard for how to load the post data.
> fix(topics): load post data using more standard `request.body`

- sefaria/model/linker/ref_part.py
- sefaria/model/linker/ref_resolver.py
- sefaria/model/linker/tests/linker_test.py
loosen requirement that trie lookups for book names needs to match NAMED parts.
Now it can match any type but can only split NAMED parts.
> Make ref part type more lenient

- static/js/TopicSearch.jsx
This feature broke due to a recent refactor. JSON stringifying now happens lower down in the call stack.
> fix(topics): Fix add topics from sidebar feature.

- sefaria/utils/tests/util_test.py
- sefaria/utils/util.py
Fix for the truncate_string function. The function didn't handle properly cases where the first closing tag of an html element appeared after the "max-length" limit, an example of it is the truncation of Akeidat Yitzchak 83:1:6 found at the Zimri topic page.
Added condition that ensures the result is shorter than "max_length", and a test that would've failed without the fix.
> Bug/sc 28279/text truncation fails for source on zimri

- sefaria/model/tests/text_test.py
- sefaria/model/text.py
When using the texts API with the `return format` param set to `'text_only'`, there was an extra space left where HTML tags were taken out. (See the image below, the ב was originally wrapped in `<big></big>` tags, which are being stripped out in this case). 
1. In `sefaria/model/text.py` in `AbstractTextRecord`, I modified the `remove_html` function to replace the tags with an empty string, as opposed to a space. If the tag is `<br>` then it is replaced with a space. 
2. In `sefaria/model/tests/text_test.py` I added a test to make sure we handle both cases (`<br>` vs all other html tags) as expected. 
- Recommendations for further testing?
> Fix Space API Bug

- reader/views.py
only staff member can add index or edit text info
staff_member_required decorator wad added to edit_text_info in reader/views.py.
> fix: only staff member can add index or edit text info.

- static/js/StaticPages.jsx
The jobs page shows that there are "no jobs" while the data call to Strapi is being made. On slow internet connections, the job listings can take a short while to load, while the user may be given the impression that there are no jobs and leave without waiting. This PR fixes that to show that the page is in a loading state until it's received the result of the call. 
* A new state variable was added to keep tracking of the loading state for the network call. Once the call is received, the status of whether there are job listings available becomes known.
* The status of whether there are jobs listing available was also refactored to variable
> Fix "flash" of "no jobs" on Jobs page

- reader/views.py
- sefaria/helper/tests/topic_test.py
- sefaria/helper/topic.py
- sefaria/model/schema.py
- sefaria/model/tests/topic_test.py
- sefaria/model/topic.py
- static/js/TopicEditor.jsx
The "disambiguation" field of topic titles was not sent to the client. As a result, when editing a topic with disambiguations in its title, the inconsistency prevented the server from properly updating the topic object. This PR fixes the issue by making the client extract the disambiguation from the title string and format the title object similarly to how it is represented in the database. The server code was also modified to accommodate the new format.
update_topic_titles in server
prepData in TopicEditor.jsx
> Bug/sc 28476/error when trying to add captions for images

- reader/views.py
Previously, the Category API assumed a 'json' parameter being passed in request.POST, but adminEditorApiRequest in sefaria.js passes a POST body instead.  Therefore, the Category Editor stopped working.
I simply allowed for both options  -- 'json' in request.POST or a body -- in case someone wants to edit the category not using the Admin Editor.
> fix(Category API): allow for json or body in POST

- requirements.txt
- sefaria/image_generator.py
This PR does 2 things: 
1. It alphabetizes (well, sort of pip is weird) the requirements file
2. It re-introduces the fallback import that existed in older versions of python-bidi. This lib went through a change that re-implemented it in Rust and caused much despair and broke `api/img-gen` for Hebrew previews, changed the import syntax and caused platform specific install issues. 
A further version update restored the old python implementation. This PR restores the code to the use the latest version and the older python implementation and fixes issues in https://github.com/Sefaria/Sefaria-Project/pull/1975
> Requirements organize

- static/js/sefaria/sefaria.js
The URLs were over 3800 characters because the pipe character gets encoded with 3 characters: "%7C", but the comparison treated the pipe character as one character.
Instead of comparing the length of `${hostStr}${last}|${encodedRef}${paramStr}` to 3800, it's necessary to encode `${hostStr}${last}|${ref}${paramStr}` and compare that to 3800 instead.
> fix(Topic Pages): getBulkText bug that led it to generate long URLs

- static/js/sefaria/sefaria.js
This addresses getBulkText sending out 3800 character URLs.
Even though a previous attempt was supposed to have fixed this, in one case, encodeURI was used and in another, encodeURIComponent.  This is problematic because encodeURI doesn't encode colons so the previous attempted fix did not do the job.  This PR makes both cases encodeURI.
> fix(Topic Pages): encodeURI should be used instead of encodeURIComponent

- sefaria/helper/category.py
We sometimes have categories with a book inside the category with the same title. For example, the category "Zohar" has the book "Zohar" inside of it.  The Category Editor doesn't work properly in this case.  
The Category Editor previously would look to re-order a book without checking that its path is inside the category being re-ordered.  This was a reasonable assumption to make in most situations, but in the above case, this means that the book "Zohar" could get re-ordered when the intention was to re-order the category "Zohar".  I fixed this by only looking for books to re-order that are actually inside the category being re-ordered.  In the code, this means an Index is only loaded when its `categories` property is identical to the `cat_path` being re-ordered.
> fix(Category Editor): do not look for books that are not in the category being reordered

- static/css/s2.css
- static/js/Editor.jsx
The "Add Source" button should stay visible after the user starts typing. Clicking it will add a new line.
I wrapped also "paragraph" nodes with a "button" div, providing this button div with "onClick" functionality of moving the anchor to end of line and invoking the already-implemented (overridden) editor "insertBreak" function
> Feature/sc 19410/always show add button in new editor

- static/css/s2.css
- static/js/Editor.jsx
The last "plus button" feature added to new editor caused each text line to be 'insensitive' to clicks an hovers, disrupting creation and deletion of links within paragraph text. 
I added a handleClick method to the addNewLine plus button which should distinguish between click on the actual div and the pseudo ::before element. Also, I added moveAnchorToEndOfClosestParagraph method so that new lines that are added via the button will be created at the end of the paragraph and not before the closest link.
> fix new editor links addition, clikcking on and removal

- static/js/UserProfile.jsx
Fixes an issue where one user coudl see the new/old sheet editor toggle of another user when viewing their profile.
Added a check in the client code to check that the profile being viewed was the one also logged in, before rendering the toggle.
We should really refactor the profile response object to not include that data from the backend at all in such a case
> Bug/sc 29084/bug users can see other users sheet editor

- static/css/s2.css
- static/js/NavSidebar.jsx
We were confusingly using both h3 and h1 in Modules and then styling the h3 and h1 tags to look exactly the same.  This PR makes all ModuleTitles use h1s.
1.  Re-factor `ModuleTitle` to not have h1 as a parameter
2. Change any uses of `ModuleTitle` that pass h1 to a prop to no longer pass h1
3. Change `AboutTextCategory` to use `ModuleTitle` instead of h3.
4. Change css to no longer style h3s to look like h1s.
5. Two special cases of CSS styling had to be dealt with here as well.  The "Support Sefaria" module was using an h3 previously and so its CSS styled an h3 tag.  It no longer is.  Also, text category pages have special styling for the name of the category to show the h1 header in all upper case letters.  I had to change the CSS and add ".contentInner" so that only the text category …
> chore: refactor ModuleTitle so that h1 is always used

- sefaria/model/topic.py
a recent refactor of the get_aggregated_urls_for_authors_indexes function in the Topic model has left a type that cuased a bug that prevented certain author topic pages from loading. This PR fixes the typo
> fix(topics_api): fixed typo that caused bug

- static/css/s2.css
This fixes a visual issue with the mobile web nav menu where you could see extra space and drop shadow that made the menu look broken
Removed the width from the original css of the autocompleter placeholder and only added it under condition that it `:has()` children
> Fix a visual glitch on mobile-web nav

- static/css/s2.css
- static/css/unbounce-banner.css
- templates/base.html
MarCom is evaluating using Unbounce for their modal and banner needs. Unbounce calls their banners "sticky bars". Unbounce by default does not provide the option for their sticky bars to have the desired behavior. Unbounce does not shift the page down when their sticky bars are shown. A solution using only CSS is provided to allow for Unbounce's sticky bars to mimic Sefaria's previous banners visually and behaviorally.
A new CSS file is added `unbounce-banner.css` to readjust parts of the web application and static pages only if an Unbounce banner is present on the page to remove visual glitches.
* The existing CSS is deployed to the following [cauldron](https://unbounce2.cauldron.sefaria.org)
* This depends on https://github.com/Sefaria/Sefaria-Project/pull/2033 and that should be …
> Visual support for banners from Unbounce

- docs/openAPI.json
The goal of this PR was to make a bunch of small requested refinements to the OpenAPI spec. 
All of the changes were made in `docs/openAPI.json`. Here are the following changes:
1. Removing the documentation for the POST of `recommended-topics`, since it effectively retrieves the same information as the GET request, and is restricted by the Django requirement of a CSRF token. As a result, it's not ideal for third-party interactive documentation. 
2. Adding an enriched description of 'link type' for the `topics-graph` endpoint, with a link to our topic ontology. Adding pre-filled examples of link types to enhance the user experience. 
3. Rearranging some of the data in the `shape` API for testing purposes. More work on that in a subsequent card. 
The spec was tested, and all desired …
> Improvements to the API Docs

- sefaria/helper/llm/tests/topic_prompt_test.py
- sefaria/helper/tests/linker_test.py
This PR fixes 2 failing tests
- test_get_commentary_from_link_dict
- test_make_find_refs_response_linker_v3
- test_get_commentary_from_link_dict: This test is one of the tests testing the interface between Sefaria-Project and the sefaria-llm-interface package. A return value had changed slightly and required `as_dict()` to convert it back to JSON.
- test_make_find_refs_response_linker_v3: This test only runs when the linker is enabled. It started failing because of the introduction of new function that wasn't mocked.
> Fix various failing tests

- .github/workflows/continuous.yaml
We have a problem that if steps fail in the continuous pipeline, the next steps will skip rather than fail, and thats a bad signal for ability to merge the PR. 
This PR attempts to fix that by adding some explicit checks and failures
> Try to get Continuous Pytests to explicitly fail if any previous steps failed

- sefaria/model/schema.py
- static/js/Editor.jsx
This PR defines a custom renderEnglishElement function to avoid rendering English source text as RTL when a Hebrew word is found within the text
return value of BoxedSheetElement in Editor.jsx
> make English source text elements always be rendered LTR

- static/js/BookPage.jsx
- static/js/CalendarsPage.jsx
- static/js/CollectionPage.jsx
- static/js/CommunityPage.jsx
- static/js/MyNotesPanel.jsx
- static/js/NotificationsPanel.jsx
- static/js/PublicCollectionsPage.jsx
- static/js/SearchPage.jsx
- static/js/TextCategoryPage.jsx
- static/js/TextsPage.jsx
- static/js/TopicPage.jsx
- static/js/TopicPageAll.jsx
- static/js/TopicsPage.jsx
- static/js/TranslationsPage.jsx
- static/js/UpdatesPanel.jsx
- static/js/UserHistoryPanel.jsx
- static/js/UserProfile.jsx
Removing the footer from where it appears on the site. 
In each of the files listed in this PR:
- The `<Footer />` component was removed
- The import statements importing the component were removed
- Any logic surrounding when to render the footer (which was infrequent) was removed as well. 
- Do we want to delete the component itself (i.e. `Footer.jsx`), I did not do that yet, but can if we think it's right.
> Remove footer

- static/css/s2.css
- static/js/AboutBox.jsx
- static/js/VersionBlock/VersionBlock.jsx
- static/js/sefaria/sefaria.js
Show all primary versions in the about box (from different languages). Show all versions that are not source in translations box.
That also fixes 2 bugs:
1. hidden versions that were shown in neither boxes.
2. number of translations in the resources panel unfit to the number of shown translations
Changes Sefaria functions  getSourceVersions and getTranslations for returning the right versions. That includes changing 2 functions they have used into one.
Changing the init value of versionLangMap in AboutBox to empty object rather than null, for consistency.
Removing the 'en' version from the source versions, for avoiding double VersionBlocks when it is a source version.
css change for selecting only the very first VersionBlock only if there are many languages.
> feat(about and translations): show all translations that are not source on the translations box, and all primary versions on the about box

- static/js/CommunityPage.jsx
- static/js/Footer.jsx
- static/js/Header.jsx
- static/js/NavSidebar.jsx
- static/js/TextsPage.jsx
- static/js/TopicPageAll.jsx
- static/js/TopicsPage.jsx
Remove community menu links from homepage (`Collections`, `Join the Conversation`, `Join the Community`). 
The `<Modules />` component in `NavSidebar.jsx` renders the sub-modules based on what's needed in the sidebar where `<NavSidebar />` is called. The core code for these widgets remains inside the `NavSidebar.jsx` file, and they remain as possible modules within `<Modules />`  for `<NavSidebar />` to call (i.e. so they can be called on the `Community` page without breaking functionality). 
The strategy here was to remove the links and the specific `Join the Conversation`/`Join the Community` where they are called, so within the library no one will encounter these widgets. 
Additionally, the `Collections` and `Community` links were removed. 
1. `static/js/CommunityPage.jsx` - Remove …
> Remove Community Menu Items

- sefaria/views.py
- static/css/s2.css
- static/js/NewsletterSignUpForm.jsx
- static/js/StaticPages.jsx
There were a few different problems with subscribing to the newsletter on the front-end and back-end.  On the back-end, there was an error because the only input to the subscription function provided was the user's e-mail, whereas our CRM requires first and last name also be provided.  Moreover, the error on the back-end was not handled properly causing the user to see the entire HTML error message that was generated by django.  
1.  The back-end should catch the TypeError generated when no first name is provided so I changed the exception handler to `except (TypeError, ValueError) as e:`.
2. We can use the NewsletterSignUpForm component which is currently used in a few different places in the site which requires the user provide a first name and last name so that the error doesn't occur …
> Bug/sc 29278/i clicked sign up to get updates on the https

- sefaria/views.py
Sources on topic pages didn't display source text when default translation language wasn't Enlgish. This is due to the fact that bundle_many_texts doesn't return 'he' text when translation_language_preference is passed.
Changed bundle_many_texts to return 'he' text regardless of translation_language_preference
> Fix: Make bundle_many_texts API endpoint return source text even when translation_language_preference is not None

- static/js/TopicPage.jsx
This adds a new topic page dedication for Parashat VeZot HaBerakhah that will stay permanently.
> Topic Page Dedication for Parashat VeZot HaBerakhah

- build/linker/Dockerfile
- static/js/TopicPage.jsx
Currently analytics tracking on topics pages tries to extract the categories of each ref on the topics page. This causes the whole site to crash if a single ref has a parsing issue. Instead, we'll use optional chaining to avoid a hard crash in this case.
> Fix topics analytics undefined index

- static/js/StaticPages.jsx
The Hebrew mobile title displayed מוצרים של ספריא instead of המוצרים של ספריא. This code corrected the Hebrew copy. Web was unaffected, since no page title for the web display. 
1. `static/js/StaticPages.jsx` - Fixed Hebrew copy
> Products Page: Fix Hebrew mobile typo

- sefaria/search.py
Sheets are currently being searched based on tags which do not exist in every sheet.
1. Deprecate tags including `make_sheet_tags`
2. Created a new function based on existing code since it gets used twice now: `make_sheet_topics`
> chore: deprecate tags and create new function make_sheet_topics

- sefaria/helper/linker.py
- sefaria/model/category.py
- sefaria/model/linker/category_resolver.py
- sefaria/model/linker/has_match_template.py
- sefaria/model/linker/linker.py
- sefaria/model/linker/match_template.py
- sefaria/model/linker/named_entity_resolver.py
- sefaria/model/linker/ref_resolver.py
- sefaria/model/linker/referenceable_book_node.py
- sefaria/model/linker/resolved_ref_refiner.py
- sefaria/model/linker/tests/category_matcher_test.py
- sefaria/model/linker/tests/linker_test.py
- sefaria/model/linker/tests/resolved_category_test.py
- sefaria/model/schema.py
- sefaria/model/text.py
Prevents categories and books from being caught using ibid context
- adds `match_templates` to categories so they can be caught independently
- add `CategoryResolver` class to match categories
- use `CategoryResolver` on `Linker` to first find categories and only then look for citations. 
- refactor out methods relating to match templates from `TitledTreeNode` into interface `HasMatchTemplates` so it can be reused for any object that has match templates
- pull out `with_failures` variable from `RefResolver` so all logic is in `Linker`. This helps `Linker` use failed categories to still search for refs.
> Prevent ibid for categories and books

- sefaria/helper/linker.py
'or True' was accidentally left in the code. The intention was to remove the 'else' clause since going forward linker v3 will be run for both English and Hebrew.
> refactor(linker): remove 'or True' from the linker API.

- static/js/TextRange.jsx
We want to add an exception for Guide for the Perplexed so that segment numbers don't show for the text.
> feat: [sc-29651] Remove numerals from Moreh Nevukhim

- static/css/s2.css
- static/font-awesome/css/font-awesome.css
- static/js/ConnectionsPanel.jsx
in static/js/ConnectionsPanel.jsx changed the props passed to ToolsButton,
created a designated .fa-X:before in static/font-awesome/css/font-awesome.css
> Change "Share on Twitter" to "Share on X" as well as change the logo

- static/css/s2.css
- static/js/StaticPages.jsx
Adding the Gray Developer Box (previously commented out as requested) to the products page. 
All in `static/js/StaticPages.jsx`:
1. Switching `<p>` to `<div>` to better conform to style spec
2. Uncommenting the component
3. Switching the urls from `example.com` to https://developers.sefaria.org/docs/powered-by-sefaria
> [Products Page] Gray Developer Box

- static/js/StaticPages.jsx
- templates/static/he/ways-to-give.html
Using Classy's short name URLs prevents the the channel source codes from being parsed by Classy's tracking system. Classy URLs need to use the full form actual URLs instead of the short name aliases
This changes all the URLs to use the actual URL instead of the short name alias with the channel source codes attached
> Change donation links to not use use short names

- docs/openAPI.json
The `limit` parameter was missing from the documentation of the `api/topics` endpoint. (Known in the dev portal as [All Topics](https://developers.sefaria.org/reference/get_api-topics)). 
The documentation of the parameter, with a description and two examples was added to `docs/openAPI.json`.
> Add missing topics param

- sefaria/search.py
Reindex cronjob was failing when a text has no versions
> fix(search): skip index if there are no versions

- static/js/AboutBox.jsx
- static/js/BookPage.jsx
- static/js/CalendarsPage.jsx
- static/js/CollectionPage.jsx
- static/js/CommunityPage.jsx
- static/js/NavSidebar.jsx
- static/js/NotificationsPanel.jsx
- static/js/PublicCollectionsPage.jsx
- static/js/TextCategoryPage.jsx
- static/js/TextsPage.jsx
- static/js/TopicPage.jsx
- static/js/TopicPageAll.jsx
- static/js/TopicsPage.jsx
- static/js/TranslationsPage.jsx
- static/js/UserHistoryPanel.jsx
- The goal of this PR is to clean up the components `<Module/>`, `<Modules/>` and `<ModuleTitles/>` to be more specific in their naming, to all be prefaced with `Sidebar` since they are all related to the Sidebar. 
- The props for `<NavSidebar />` were also renamed from `modules` to `sidebarModules`
- In all of the files there are changes, the aforementioned modules are renamed, and import statements are adjusted. 
- This was tested extensively locally, however I'd appreciate if the reviewer was able to pull locally and check just to ensure nothing was missed accidentally.
> Naming Clean Up

- api/views.py
- reader/views.py
- sefaria/model/text.py
- sefaria/system/decorators.py
- sefaria/system/exceptions.py
Improve error messaging and remove 500 errors on the texts API (v1 and v2)
1. `sefaria/model/text.py` - Write more robust error message to be more helpful for our third party users. 
2. `api/views.py` - Properly catch error for Book Level Complex Texts, and report helpful error message.
> Improve error messaging and remove 500 errors

- static/js/ReaderApp.jsx
prevent converting of commentary ref to base refwhen clicking a search result from side bar.
ReaderApp.jsx
add `convertCommentaryRefToBaseRef` param to `replacePanel`, and set it to false when calling from `handleSidebarSearchClick`
> fix(onSidebarSearchClick): prevent converting of commentary ref to base ref

- sefaria/views.py
We had recently corrected a bug throughout the API which incorrectly handled boolean parameters being passed as 0s or 1s. They were handled as strings, and therefore constantly evaluating as `true` and causing unexpected behavior, we made an effort to make sure they were all properly being passed as ints. This PR fixes one instance that was missed in that initial sweep - based on user feedback. 
1. `sefaria/views.py` - Cast the `useTextFamily` param results to an int. 
- Tested locally and works. When set to `1`, the response includes the primary category of the text.
> `bulktext` API Correct Handlings of 1/0 Booleans

- static/js/AboutSheet.jsx
- static/js/CollectionPage.jsx
- static/js/ConnectionsPanel.jsx
- static/js/Editor.jsx
- static/js/Header.jsx
- static/js/ImageCropper.jsx
- static/js/Misc.jsx
- static/js/ProfilePic.jsx
- static/js/SearchSheetResult.jsx
- static/js/Sheet.jsx
- static/js/SheetMetadata.jsx
- static/js/UserProfile.jsx
Pulled out ImageCropper code from ProfilePic to make ImageCropper a reusable component. This makes ProfilePic a much simpler component and allows for reusing ImageCropper in other places.
- Moved ImageCropper out of ProfilePic
- Moved ProfilePic out of Misc.jsx. This became necessary to avoid circular dependencies since ImageCropper relies on other code in Misc.jsx. As a side benefit, ProfilePic is a large enough component that it warrants its own file.
This change is in preparation for allowing image cropping for other admin tools, such as on the topics admin page.
> Reusable ImageCropper Component

- static/css/s2.css
This is a temporary fix for the display of Strapi banners to fix the spacing in the header when the banners are closed. The `setContainerMode` code for adjusting the class on `<body>` used to work, but is currently not working. That code will need to be refactored in the future.
> Fix display of Strapi banners on static pages

- reader/views.py
- sefaria/helper/topic.py
- sefaria/model/topic.py
- sefaria/urls.py
- static/css/s2.css
- static/js/AdminEditor.jsx
- static/js/ImageCropper.jsx
- static/js/Misc.jsx
- static/js/ProfilePic.jsx
- static/js/TopicEditor.jsx
Adds ability to upload secondary topic images through the topic admin editor
- add `_api/topics/images/secondary` API for uploading and deleting secondary topic images.
- refactor existing topic image API so that it handles files in a more standard way (using the file object that's uploaded as opposed to using the base64 string)
- Pull topic editor code from Misc.jsx into TopicEditor.jsx where it belongs
- Allow ImageCropper to take a widthHeightRatio prop to control the ratio of the cropping square.
> Secondary topic image

- .github/workflows/continuous.yaml
This adds a workflow library that filters files and checks before deploying a pytest sandbox to see if the PR even contains python changes This should hopefully allow client side changes to move through the CI piepline more easily
Adds dorny/paths-filter action to the continuous workflow and uses it to check for python file changes in the PR 
It then uses that result in deciding whether to run the sandbox and pytest jobs in the workflow.
> Only run pytests when python files are changed

- .github/workflows/integration-testing.yaml
- e2e-tests/globals.ts
- e2e-tests/tests/topics.spec.ts
Tests to verify the basic functionality of topic pages, ensuring that user information depends on environment variables and is not exposed.
Added tests to e2e-tests/tests/topics.spec.ts simulating accessing topic pages as a normal and super user in en and he interfaces, vertifying that a redirect happens when a sourceless topic mage is visited in non-superuser mode.
In addition,  created testUser and testAdminUser objects in e2e-tests/globals.ts making them rely on env var data
> Tests verifying basic topic page functionality

- sefaria/local_settings_example.py
The port number is now required when connecting to production search from local. Modified the docs to reflect this.
> docs(local settings): add port number to docs explaining how to connect to search

- static/js/NavSidebar.jsx
There was a `<ModuleTitle/>` in `NavSidebar` that was missed when we renamed to `<SidebarModuleTitle/>`
In `static/js/NavSidebar.jsx` component renamed as described above. 
Checked branch for any other breaking instances of `<ModuleTitle/>`. None found.
> Fix a missed module rename

- sefaria/helper/crm/crm_mediator.py
- sefaria/helper/crm/salesforce.py
- sefaria/urls.py
- sefaria/views.py
Sefaria currently provides a backend API for subscribing to newsletters. The API does not currently support subscribing to multiple and different newsletter lists that Sefaria provides. This PR gives that ability. A code update to Salesforce will also be necessary to support allowing multiple newsletter.
* Adds a new payload item as a list of strings for the `api/subscribe` endpoint to take other newsletter lists besides the default included for every user. Either none or multiple newsletters can be sent. Duplicates and invalid mailing lists are ignored.
* Adds a new `api/newsletter_mailing_lists` endpoint to show the available newsletter mailing lists a user can be susbscribed to. The management of these lists are done through Salesforce/ActiveCampaign. The endpoint will be used by …
> Update subscribe endpoint for multiple newsletter subscriptions

- sefaria/views.py
We had recently corrected a bug throughout the API which incorrectly handled boolean parameters being passed as 0s or 1s. They were handled as strings, and therefore constantly evaluating as `true` and causing unexpected behavior, we made an effort to make sure they were all properly being passed as ints. 
The issue with int casting, is that one has to handle cases where no param is passed since optional. 
This PR casts `useTextFamily` param results to an int if present, and if not returns `None`. This ensures continued topic source functionality. 
1. `sefaria/views.py` - Cast the `useTextFamily` param results to an int, and improve default param logic of underlying function.
> Fix API and ensure no broken topics

- docs/openAPI.json
Add missing documentation for the `always_consonants` parameter on the words API.
> Add documentation for `always_consonants`

- static/css/s2.css
- static/js/TextRange.jsx
add 'heOnly' to class when we show rtl translation in sidebar (similar to what we have before rtl).
add css rule for overriding heOnly rule that shows also the primary.
> fix(sidebar): show correctly rtl translation in sidebar.

- static/css/s2.css
- static/js/FontSizeButton.jsx
- static/js/LayoutButtons.jsx
- static/js/ReaderDisplayOptionsMenu.jsx
- static/js/SourceTranslationsButtons.jsx
- static/js/common/ToggleSwitch.jsx
- static/js/common/ToggleSwitchLine.jsx
- static/js/constants.js
Add html attributes:
1. role dialog to the whole menu.
2. roles radiogroup and radio, aria-label and aria-checked to source translation buttons and layout buttons (aria-labels for layout buttons added to constants.js).
3. role switch, aria-labelledby and aria-checked to toggle switches.
4. role button, aria-labels to font size buttons. and set alt of img tags to an empty strings (prevents duplication with aria-label).
HTML tags: use button for actions (change font size), use input for anything else.
Note:
We're not supporting keybaord navigation, and this was not changed.
> Rtl accessibility

- static/js/TopicPage.jsx
- static/js/sefaria/sefaria.js
This PR ensures that unpublished sources are no longer displayed on the topic page. Also, when now hitting the "Publish" button, not-reviewed prompts are not published.
> hide unpublished sources in topic page

- sefaria/model/text_reuqest_adapter.py
Infinite loading bug found in "On Providence".  The reason turned out to be that there was an edge case not previously considered -- a default child with depth 1.
The /api/v3/texts/ needs to check if the ref has a default child ref.  "On Providence" should yield "On Providence<d>".  This also solves an existing bug with Otzar Midrashim where there are default nodes with depth 1.
> fix(Texts API): check for default child ref

- static/css/s2.css
- static/js/Misc.jsx
- static/js/UserProfile.jsx
Aligning the profile page on sheets to the updated spec
1. `static/css/s2.css` - Aligning styles with spec. 
2. `static/js/Misc.jsx` - Removing icons, topic tags from SheetListing and CollectionListing
3. `static/js/UserProfile.jsx` - Removing and rearranaging according to spec, removing filter and search on list items. 
- Some outstanding font questions to be cleared up
> [Sheets][Desktop] My Profile

- sefaria/system/exceptions.py
We recently updated the slugs for the pages in the Readme docs. This PR catches the instance of the "old" slug, and updates it to match the new one. 
1. In `sefaria/system/exceptions.py` - Slug of URL was updated, the word `structure` was swapped for `schema`.
> fix(errors): Update URL to match new devportal slug

- static/js/TextList.jsx
When loading "Rashi on Genesis 1:2:1", we should load "Genesis 1:2" in the main panel with Rashi's links in the side panel.  Sometimes, due to a seeming race condition, it wouldn't load the Rashi links.  When the links didn't load, it's because there was no section "Genesis 1" in the ref cache and so this call below to this.getSectionRef() was evaluating to "Genesis 1:2" instead of "Genesis 1".  The links at this point have loaded for "Genesis 1" but not yet for "Genesis 1:2".  It would then try to load the links from the link cache for "Genesis 1:2" which it couldn't find.  
See this code from TextList.jsx.
```
preloadSingleCommentaryText(filter) {
//console.log('preloading single commentary')
// Preload commentary for an entire section of text.
this.setState({textLoaded: false});
var …
```
> fix(Connections Panel): derive section ref if not cached yet

- static/js/ConnectionsPanel.jsx
Edit text works with old dichotomy he/en.
So the language code that sent to the server should be en for ltr and he for rtl.
But in the client side editText function, we should get the versionTitle from currVersions by the master panel language (which is en for translation and he for primary).
This PR fixes the function to the right languages.
> Fix edit text

- django_topics/admin.py
- reader/views.py
- requirements.txt
- sefaria/helper/topic.py
- sefaria/urls.py
- static/js/NavSidebar.jsx
- static/js/TopicLandingPage/TopicsLandingPage.jsx
- static/js/sefaria/sefaria.js
This pull request introduces a new trending topics API and related frontend components. The backend has been updated to handle caching, filtering, and returning a configurable number of trending topics based on data from google analytics. The frontend now includes a new "Trending Topics" sidebar module to display the fetched topics.
Django Backend:
Added a trending_topics_api endpoint that returns a filtered list of topics.
Modified the get_trending_topics helper function to accept a variable n and handle topic filtering.
Added caching decorators to the get_trending_topics function for improved performance.
Frontend:
Introduced a TrendingTopics sidebar module to display trending topics dynamically.
Added logic in sefaria.js to fetch and cache trending topics from the API.
Updated the …
> Trending Topics for Topic Landing Page

- scripts/scheduled/metrics.py
- sefaria/model/text.py
Fixing a non graceful error with word_count in text that created some old schedule scripts to fail
text.py try catch in the word_count function. and in the metrics.py script mongodb api function names changes. save -> insert_one and count -> count_documents.
> Feature/sc 31547/metrics webpage

- requirements.txt
- static/css/s2.css
- static/js/NavSidebar.jsx
- static/js/TopicLandingPage/TopicsLandingPage.jsx
This PR introduces two new sidebar components for the Topic Landing Page:
1. Topic Category List: Displays a categorized list of topics with links to their respective pages.
2. A-Z Topics Link: Adds a link to the all topics a-z page.
> Add Topic Category List and A-Z Topics Link to Sidebar

- static/js/sefaria/sefaria.js
> Rtl cache ssr

- static/js/sefaria/sefaria.js
This PR ensures that manual descriptions for topics on the topic page are displayed when available. It fixes an issue where certain descriptions were not appearing
> Show (publish) Manual Descriptions for Sources on Topic Pages

- e2e-tests/tests/interface-language-is-sticky.spec.ts
Tests the following:
**Hebrew/English Language**
* English source
* Bilingual source
* Hebrew source
resulting in 6 tests
> Validate interface language is sticky when source language changes

- e2e-tests/globals.ts
- e2e-tests/tests/interface-language-is-sticky.spec.ts
- e2e-tests/tests/translation-version-name-appears-in-title.spec.ts
- e2e-tests/utils.ts
> Language selection playwright tests

- static/css/s2.css
- static/js/ConnectionsPanelHeader.jsx
- static/js/ReaderPanel.jsx
changes:
ConnectionsPanelHeader - remove Hebrew UI from showOneLanguage
ReaderControls - do not default ConnectionsPanel language to Hebrew.
CSS - align buttons to center.
> Add language toggle to sidebar in Hebrew UI

- static/js/Header.jsx
The `New Additions` link in the dropdown was linking to notifications, this moves it to link to `/updates`/ 
In `static/js/Header.jsx` changed the URL.
> Fix link in dropdown

- sefaria/model/tests/library_test.py
- sefaria/model/text.py
Badly formatted citations were generating a KeyError and preventing loading of segment in Rashba on Megillah
We are now handling the KeyError.  The segment loads properly.  The badly formatted citation simply appears as regular text and is not picked up as a link.
> fix(Links): safely fall back when keyerror is returned

- static/js/ReaderPanel.jsx
- static/js/SearchSheetResult.jsx
We have a feature in production that was not implemented when we created the Sheets With Ref Page this summer.  The feature is that if a user has "Exodus 7:1" open in the reader and opens a sheet from the sidebar, the sheet will scroll to highlight the source "Exodus 7:1" in the sheet.  In modularization, when a user tries to open a sheet from the reader, they are taken to a new page, the Sheets With Ref Page which displays all the sheets for the given ref with appropriate topic filters (like the Search Page).  However, previously in the modularization branch, when a user would click one of these sheets, the sheet would not scroll to "Exodus 7:1" and highlight it.  This PR corrects this.
There's a function in ReaderPanel, handleSheetClick, which is used in production to implement this …
> chore: pass highlightedRefsInSheet from SheetsWithRefPage

- node/webpack.config.js
Changes the webpack config so that babel uses the new jsx transform so React is available globally and does not need to be imported in every file 
Added `{ runtime: 'automatic' }`
```
presets: [
['@babel/react', { runtime: 'automatic' }],
'@babel/preset-env'
],
```
To the `rules` block of `baseConfig` in the main webpack file
Will need some more verbose prod grade testing
> Attempt to fix React Undefined in SSR

- templates/base.html
Analytics parameter traffic_type to be sent with every event from internal Sefaria team so that to exclude their data from our user data. 
a addition to all events sent thorough gtag, the change is in templates/base.html
This is a change needed to be implemented asap so we can gather accurate data for topic pages.
> feat(analytics): traffic_type for internal users

- django_topics/admin.py
- django_topics/models/topic.py
- sefaria/model/autospell.py
A simpler cahce mecahnism for the retrievel of pools per slug - implemented as part of the Django TopicManager
The cahce is  created only after first call to get_pools_by_topic_slug ("lazy"), I tried to create it upon first initialization of of the topic manager but it's somewhat complicated, since the actual models (schemas) are not yet created at this point, so it's  not possible to get the data from the tables at this stage.
> Pool Cache on Django's TopicManager

- static/css/s2.css
- static/js/Header.jsx
- The header icons were not vertically aligned, this PR cleans it up with CSS
- The help button was mistakenly removed, this PR reinserts it and centers it properly
1. `static/css/s2.css` - Adjusting some margins, mostly just making sure each div wrapping each icon svg was displaying its contents as centered. 
2. `static/js/Header.jsx` - Adding the help button
- Right now, the help button seems to disappear in mobile-web, is this by design?
> Clean up Header Icons

- django_topics/models/topic.py
- reader/startup.py
- static/css/s2.css
- static/js/NavSidebar.jsx
- static/js/TopicLandingPage/TopicLandingSearch.jsx
- static/js/TopicLandingPage/TopicsLandingPage.jsx
Added an "Explore All Topics" prompt for mobile users on the Topic Landing Page. The prompt smoothly scrolls to the Browse Topics section when clicked.
Make slug_to_pool cache map initialize on server start
> "Explore All Topics" prompt for mobile, Initialize Topic Pools Cache on Server Start

- django_topics/models/topic.py
Refactors sample_topic_slugs to use queryset-level slicing for improved efficiency. Replaces in-memory random.sample with database-level random ordering. Cleans up exception handling.
> Optimize topic sampling with queryset slicing

- static/js/explore.js
Explicitly add direction ltr to the svg element.
This svg building is based on the assumption of rtl also for the Hebrew interface.
This fixes the location of Hebrew strings to be within the text boxes, and of the Hebrew book titles not to be over the horizontal bars.
We can solve the first problem (text out of its box) by changing the text-anchor, but changing the other problem seems much more complcated. It seems that the text-anchor: end is there from the first place due this.
> Fix visualization in Hebrew

- static/css/s2.css
- static/js/TopicPage.jsx
For topic pages, bilingual mode doesn't work
Very simple issue.  We simply weren't setting "bilingual" mode.  I changed one line and a little CSS:
> fix(topics): [sc-32232] "Source+Transaltion mode" in the Hebrew UI on topic pages seems to be non-functional

- static/js/Misc.jsx
- static/js/context.js
This adds support for a new separate enumerated field that was added to Strapi for modals and banners. Users who are logged-in or logged-out can now be targeted. The default option for this field in the content type targets all users, both logged in and logged out.
* Pulls the new enumerated field from Strapi
* Changes the conditional logic structure for when a modal or banner should be shown
* To reduce future confusion, 3 options were chosen: logged-in-only, logged-out-only, and both logged-in and logged-out.
* Since all the previously existing flags depend on whether a user is logged in, the new field overrides the existing flags when choosing the option for logged-in- or logged-out-only users.
> Support to target banners and modals based on logged-in status

- static/js/Header.jsx
- static/js/NotificationsPanel.jsx
Removes the "Mark All As Read" button from the notifications page, while ensuring that the current behavior of the notifications are marked as read on scroll is retained. 
1. `static/js/NotificationsPanel.jsx` - Removed the button and underlying `all` function. Note, the `markAsRead` function and marking as read on scroll are retained. 
2. `static/js/Header.jsx` - Slight code cleanup for readability
> Remove "Mark All As Read" button

- sefaria/model/passage.py
This pull request includes updates to the `Passage` class in the `sefaria/model/passage.py` file to enhance type validation by introducing a list of possible types.
Enhancements to type validation:
* [`sefaria/model/passage.py`](diffhunk://#diff-6b400f0198af9f9e2d3d5c10f40475c38723e31c07d2387f5a07843e3483e1e0R24-R25): Added a new class attribute `possible_types` to store a list of valid types for the `Passage` class.
* [`sefaria/model/passage.py`](diffhunk://#diff-6b400f0198af9f9e2d3d5c10f40475c38723e31c07d2387f5a07843e3483e1e0L39-R41): Updated the `_validate` method to use the `possible_types` list for type validation, replacing the previous hardcoded checks.## Description
> feat(passage): expand possible types for passage validation

- sefaria/model/passage.py
This PR introduces a feature to load the shortest passage from a set of passages. It updates the containing_segment method to return the shortest passage based on the number of references in its ref_list. If no passages are found, it returns None.
Modified the containing_segment method in sefaria/model/passage.py to implement logic for finding the shortest passage.
> implement shortest passage loader

- static/js/Header.jsx
Adding functionality based on a prop to account for logged out menu dropdown differences between sheets and library. 
In `static/js/Header.jsx`, the `<LoggedOutDropdown />` now accepts a prop for the module, and toggles what is displayed accordingly. 
Note, for now (testing purposes) the value is hardcoded. This (as noted in the todo) will need to be refactored to inherit the Header's knowledge of which module it is in.
> [Sheets] Logged out dropdown

- static/css/s2.css
- static/js/Header.jsx
Adjusting the mobile-web secondary nav menu in sheets to account for logged in states
1. In `static/css/s2.css` a flex container for profile picture and text alignment (double check Hebrew on someone else's local)
2. In `static/js/Header.jsx` - a `module` prop, and conditional logic for what to display based on whether in sheets or library, and logged in or not. 
1. The hardcoded value will need to be replaced as per the TODO comment. 
2. In https://github.com/Sefaria/Sefaria-Project/pull/2366 I forgot to account for conditionally rendering module switcher options (i.e. when someone is in `sheets` they should have the option to return to the library or to go to the dev portal. Alternatively, if someone is in `library` they should have the option to go to sheets or go to the dev portal). I …
> [Mobile][Sheets] Logged In Secondary Nav

- static/css/s2.css
- static/js/Header.jsx
- static/js/ReaderApp.jsx
Adding the bookmarks icon to the header - conditionally if the user is both logged in and in sheets mode. 
1. `static/css/s2.css` - Styling to align the icon with the others in the header
2. `static/js/Header.jsx` - Adding the icon with conditional logic, and the module prop to `<Header />`
3. `static/js/ReaderApp.jsx` - Passing the new module prop. Note, this is hardcoded. See `TODO` for the reminder to integrate once the entirety of the header comes together. 
- A question about what to do with the module prop on `<Header />` renderings on static pages. @yitzhakc and @edamboritz curious to get your insight when you have a chance.
> Add "saved" icon to the Library header

- static/css/s2.css
- static/js/Header.jsx
- static/js/ReaderApp.jsx
Conditionally render the notifications bell in the header for logged-in sheets users only. 
1. `static/css/s2.css` - Styling and alignment for the bell. 
2.  `static/js/Header.jsx` - Conditional render logic for the icon, adding module prop to Header. 
3. static/js/ReaderApp.jsx - Passing the new module prop. Note, this is hardcoded. See TODO for the reminder to integrate once the entirety of the header comes together.
- Same question (as in https://github.com/Sefaria/Sefaria-Project/pull/2368) about what to do with the module prop on <Header /> renderings on static pages. @yitzhakc and @edamboritz curious to get your insight when you have a chance.
> [Sheets] Notifications Bell

- static/js/Header.jsx
Set the theme-able CSS button in the header to conditionally render for sheets only. 
In `static/js/Header.jsx` creating the `Create` button component and conditionally rendering it. 
The background color for the button does not seem to be automatically filling as expected given the behavior of the theme-able CSS. Same as in https://github.com/Sefaria/Sefaria-Project/pull/2383
> [Sheets] Green "Create" Button in Header

- static/js/TopicLandingPage/TopicLandingNewsletter.jsx
- static/js/analyticsEventTracker.js
- templates/base.html
Adds 'form_name', 'form_destination' ga4 event types to analyticsEventTracker
Adds inputStart JS event to analyticsEventTracker so we can just track the first input to an element
Uses these features to implement analytics for topic landing newsletter
> Form start analytics event

- static/css/s2.css
Fixing the padding on the help icon in the header. 
In `static/css/s2.css` added a margin-inline-start to match the other icons. 
Tested everything looks as expected in both Hebrew and English interfaces.
> Adjust padding on secondary nav in Hebrew language site

- docs/openAPI.json
Updates the documentation of the Name API to account for a shift in parameters. The boolean `is_ref` has now become `type` which expects a String `ref` to indicate it should return refs only. 
1. In `docs/openAPI.json` - updated the path documentation and the data schema, corrected any other references to the old boolean param. 
1. This has been successfully tested with ReadMe, and makes the expected changes.
> chore(docs): Updated Name API documentation

- sefaria/system/middleware.py
> fix(linker): exclude linker.v2 and v3 from languageSettingsMiddleware

- static/js/ReaderApp.jsx
- templates/base.html
Removes the code related to the custom topics launch banner, so that it isn't imported and doesn't show.
Most of the code related to the banner was left in case MarCom decides they want to show the banner again.
> Remove topics launch banner

- static/css/s2.css
- static/js/Misc.jsx
- static/js/common/DropdownMenu.jsx
- static/js/sheets/SheetOptions.jsx
- Refactoring the logged out language toggle to use our generic components
- In the process, consolidated `<DropdownMenuItem>` and `<DropdownMenuItemWithCallback>` into one component that can handle all possible configurations (@stevekaplan123 - would love your eyes on this in sheets to make sure I didn't break anything). 
1. Subtle class name changes in `static/css/s2.css`, the additional of an extra flexbox div to enable the languages to shuffle (i.e. have the selected language rise to the top) without interfering with the title. 
2. `static/js/Misc.jsx` - Main body of work. 
3.  `static/js/common/DropdownMenu.jsx` - Refactoring and consolidation of `<DropdownMenuItem>`
4. `static/js/sheets/SheetOptions.jsx` - Implementing the consolidated `<DropdownMenuItem>` (@stevekaplan123 - this is …
> Refactor Language Toggle

- static/js/ConnectionsPanel.jsx
In the RTL project we've change the way of categorizing texts - rather than ltr/rtl dichotomy, we have now (also) primary/translation dichotomy. The edit api still interprets he/en as ltr/rtl.
Therefore, when trying to edit ltr source or rtl translation, that are default (and therefore are missing in `currentVersions`), one got the wrong text to edit.
This PR changes the way we inquire the details of the version to edit - rather than taking it from `currVersions`, it's taken from the data itself, so we always have explicit version details.
> Fix editing default ltr source and rtl translation

- static/js/Misc.jsx
Nechama sheets in the Connections Panel stopped working in modularization.  It seems some code got deleted at some point.  This PR simply brings it back.
> fix: nechama sheets should display

- sefaria/client/wrapper.py
- static/js/ConnectionFilters.jsx
- static/js/ConnectionsPanel.jsx
- static/js/TextList.jsx
- static/js/sefaria/sefaria.js
Essay links do not show text in the Connections Panel.
1. To get essay links to show up: TextList calls getLinksFromCache instead of getLinksFromCacheAndPreprocess because the preprocess function removes essay links thus preventing essay links from ever being shown in the TextList.
2. To make sure essay links don't show up when they shouldn't show up (they recently were showing up in "All Tanakh" links in a recent bug): Links API now makes the category of essay links "essay" instead of "commentary" or "tanakh".  This way essay links will never show up when the user views commentary or tanakh.
> fix: essay links should have their own category

- sefaria/helper/topic.py
- static/js/TopicPage.jsx
This PR fixes 2 issues:
1. The curated primacy was initially generated incorrectly, based on counting ref-links with availLang filed. Now it's computed curectly based on the max existing curatedPrimacy.
2. The client didn't handle properly the case of 2 duplicate sources for one topic page (one learning-team and one by ctonjob). this pr fixes that by a more correct processing of the server-returned data.
> Fix Curated Primacy Initial Computation and Propely Handle Duplicate Refs in Text Fetching

- static/js/Editor.jsx
This pull request introduces a new function to handle nested lists in the `static/js/Editor.jsx` file. The key change is the addition of a `flattenLists` function to ensure compatibility with the new editor that does not support nested lists.
Changes to handle nested lists:
* [`static/js/Editor.jsx`](diffhunk://#diff-0edb809ee68c59c1469d28011e2d3be7af1cc5f8ab4d6a994150091983abfa41R517-R541): Added the `flattenLists` function to flatten nested lists into one-depth lists and integrated it into the `parseSheetItemHTML` function to process HTML strings accordingly.## Description
> Handle Nested Lists in New Editor

- sefaria/model/user_profile.py
- static/js/UserProfile.jsx
Before we delete editor.js and the editor toggle header, we are going to simply turn off the editor toggle header and turn on new editor for all users.
__init__ for UserProfile sets show_editor_toggle to False and uses_new_editor to True no matter what the DB says.
> chore: show_editor_toggle always False and uses_new_editor always True

- static/js/Editor.jsx
This pull request makes a minor improvement to the `parseSheetItemHTML` function in `static/js/Editor.jsx` by adding a clarifying comment to explain the purpose of replacing non-breaking spaces and line breaks in the `preparseHtml` variable.
* [`static/js/Editor.jsx`](diffhunk://#diff-0edb809ee68c59c1469d28011e2d3be7af1cc5f8ab4d6a994150091983abfa41L541-R544): Added a comment to describe the replacement of non-breaking spaces with regular spaces and line breaks with spaces in the `parseSheetItemHTML` function.## Description
> fix(editor): replace line breaks with spaces in parseSheetItemHTML

- static/js/ReaderApp.jsx
Unfortunately we're using our ouw router for saving history.
In this router we're using the index title which can contain a wuestion mark, and break the url when refreshing.
The best would be encoding components when neccesary, but the url making has a toocomplicated code with many options.
This fix takes the final stage of the url making, when we replace the first `&` to `?`, and encode the path only, with escaping from encoding slashed.
> encodeURIComponent in history

- reader/views.py
- sourcesheets/views.py
- static/js/ReaderApp.jsx
- static/js/sefaria/searchState.js
Search modularization was done this previous summer, but there is one last step that we had to put off, which is that search pages need to display differently based on active module.  This implements that change.
initialSearchType was a placeholder for activeModule.  It's now replaced.  One decision that may be questionable is to use a conversion function moduleToSearchType and place it into searchstate.js.
> chore: replace initialSearchType with activeModule

- static/js/Misc.jsx
This pull request refactors the `LearnAboutNewEditorBanner` component in `static/js/Misc.jsx` to improve state handling and ensure proper behavior when rendered on the server side. The key changes involve replacing the state initialization logic and introducing a `useEffect` hook to manage state updates.
> fix: sheets banner spacing

- static/js/ReaderApp.jsx
Revert "fix(makeHistory): use encodeURIComponent on title for encoding question marks in history."
This reverts commit ea2ddb306980a14732bbb152ae67dfdd3a1ce30e.
> fix: Prevent mangling of , (and other chars?) on URL

- static/js/ReaderApp.jsx
We want to support question marks in titles. `makeHistoryState` creates the url in a very complicated way, so it's hard to say where exactly the ref can be inserted and handle it. Here we are changing the ? to %3F after making the whole url, and before inserting the question marks that signs the params part.
using encodeURIComponent cause problems for it can run twice so in the first time it will change ? to %3F and in the second it will encode the %. Also, it seems we support commas in the url and are changing space to underscores, so encodeURIComponent do more than we want.
> Encode manually question mark in titles in makeHistoryState.

- sefaria/helper/crm/crm_connection_manager.py
- sefaria/helper/crm/dummy_crm.py
- sefaria/helper/crm/salesforce.py
This fixes the order and type of parameters sent to Salesforce. The interface language and educator fields were in the wrong order and causing Hebrew users to be signed up for the wrong version of the newsletter mailing lists.
* The existing data on Salesforce from previous submissions also needs to be fixed using a one-time script or flow to correct the order of the fields.
* The user's desired newsletters may need to be resent from ActiveCampaign in their preferred language
> Hebrew newsletter form sign up producing wrong data in Salesforce

- static/js/HeaderAutocomplete.jsx
- static/js/ReaderApp.jsx
- static/js/sefaria/sefaria.js
HeaderAutocomplete.jsx - Encode the question marks for using the url in openURL and href
ReaderApp.jsx - Return them to be question marks where we're treating them as refs.
> Encode question marks in titles from autocpmleter

- node/server.js
- static/js/sefaria/sefaria.js
Our node SSR servers are routinely overflowing their heap.
Turns out, we have unbounded caches that make sense in the browser, but not for SSR.
Clear caches managed in sefaria.js in between every Node Express request.
> Clear cache in node between requests

- reader/views.py
- sefaria/model/text.py
In previous fix we've changed also the `Ref.url` in the server side to encode question mark with `%3f`. This cause to a situation where the client side requests some ref with `%3F` and get 301 to the same url, because Django returns the question mark, and the server side thinks it's different from the normal url ref.
The `url` method now have a new default arg for getting the url without HTML encoding (i.e. with a question mark rather than `%3F`).
Noth that this method also sets the value of `._url`, and this attribute will remain encoded.
Also I've refactored the way we're replacing the last occurrence of underscore.
> Fix question mark in index title break navigation

- requirements.txt
Solve an issue with our Build actions that was causing the build to fail on some kind of python dependency issue. [See example here](https://github.com/Sefaria/Sefaria-Project/actions/runs/15412455008/job/43370277506)
Modified the `requirements.txt` to pin the celery version and remove the direct dependence on redis-py
> chore(python): fix python dependency issues

- templates/static/annualreport.html
* **Problem:** Mobile Safari intentionally downgrades a PDF that sits inside an `<iframe>` to a single static image for performance and security reasons.
* **Solution:** Replace iframe with a link on iOS to open the referenced PDF in a new tab
* A function has been added to check whether the browser is an iOS based one and to dynamically add a link to open the PDF
* An `id` has been added to the `iframe` so that it can be properly referenced
> Fix Annual Report Dispaly on iOS

- sefaria/model/tests/library_test.py
- sefaria/model/text.py
In our data we have `<a>` tags. When requestong for it our links wrapper doesn't consider that, so they can be re-wrapped, or worse, their ref attributes cab be wrapped, ruining the html structure.
This PR excludes the a tags from being wrapped.
In `get_wrapped_refs_string` the a tags are splitted out by regex, and the wrapping applied only on the other substrings.
The regex assume we have no `<a>` tags nested within `<a>` tags (which we shouldn't have).
We have 2 cases:
1. segment without <a> tags - `re.split` takes time (~3ms for 'normal' segment), and for that reason I've added an if statement that takes ~0.1ms for a 'normal' segment, so a section request will take few ms more than previously.
2. segment with <a> tags - here we apply `re.split`, and have more calls to …
> Exclude <a> tags from being wrapped again.

- static/js/Editor.jsx
Replaces divine names correctly in both Hebrew / English Slate editors. The old solution tried Transforms.setNodes, which can’t mutate a leaf’s text. We now walk all text nodes bottom-up, remove each matching leaf, and re-insert a new leaf with the updated string while preserving existing marks fixing the override.
> fix(Editor): fix divine name replacement logic

- reader/views.py
- sefaria/helper/topic.py
- sefaria/model/topic.py
- static/js/TopicPage.jsx
- static/js/TopicPageAll.jsx
- static/js/sefaria/sefaria.js
Related topics display in the sidebar on topic pages.  If we are in a topic page in the sheets module, related topics should only display if they themselves have sheets.  Likewise, in a topic page in the library module, related topics should only display if they themselves have library sources.
1.  Minor syntax change on the back-end: I'm calling topic.get_pools() instead of calling the pools object itself.  This is easier to read and I didn't know we had this function before.
2. The main change is that in the back-end,  sefaria/helper/topic.py, topic links are populated with get_pools() so taht in the front end, in TopicSideColumn, we can check if we should display the topic link given the current active module.
> chore: TopicSideColumn uses shouldDisplayTopic

- .gitignore
- static/js/ConnectionsPanel.jsx
There was an erroneous alert after trying to delete a note in addition and before the alert we want.
I simply removed it.  
Also added to gitignore some local development files (Used for cursor + palywright MCP + .env)
Testing:
I checked the error didn't pop up anymore but that the note was deleted
> Bug/sc 34949/when i try to delete a note in the hebrew

- static/js/Sheet.jsx
We're supporting spotify in the editor but not in the viewer. This PR fixes this issue.
- Add spotify option to `Sheet.jsx`.
- Use parsed url rather than raw url in the if statement. This is much clean than the regex match we're using for other options.
> Support spotify in sheets.

- sefaria/utils/hebrew.py
- sefaria/views.py
- static/js/linker.v3/main.js
Makes linker v3 the default linker version although it is still possible to specify an older version. Also makes "link" mode the default mode for wrapping citations. This means that each citation will be a link to Sefaria as opposed to opening a popup.
> feat(linker): make linker v3 default.

- static/js/Header.jsx
- static/js/Misc.jsx
- static/js/ReaderApp.jsx
- templates/base.html
**Simple Analytics (SA)** has been added alongside GA to verify event counts and isolate any `IntersectionObserver` problems. SA’s raw, unsampled logs and its stricter bot filtering will help us determine if real humans are seeing fewer impressions or if GA is inflating page views.
A couple fixed elements were wired up to validate the observer itself. The fixed elements must become fully visible at least once per session. When that happens, each of their hooks fires exactly one impression event and tags the session with a key so that it can later be confirmed through analysis.
- **Embed Simple Analytics** in base.html.
- Production script plus a dev script that points at a separate hostname, so test traffic doesn’t taint production numbers
- SA automatically strips bots it recognizes
- …
> Add SA to cross-check GA

- templates/base.html
After looking at the data being collected by Simple Analytics, it was found that the intended metadata is missing for many users. There is a possible race where the metadata would be undefined before the embed script is included and the event queue is flushed.
* Move loading of embed script to after definition of metadata
* Make embed script `defer` to ensure it's executed after metadata definition code at its place in the HTML document
* Fix various equality errors that could cause potential issues
> Fix Simple Analytics metadata collection

- static/js/Editor.jsx
This pull request introduces a new helper function to improve HTML preprocessing in the `Editor.jsx` file. The most notable change is the addition of `replaceDivWithBr`, which ensures that `<div>` tags are replaced with `<br>` tags during HTML parsing.
* [`static/js/Editor.jsx`](diffhunk://#diff-0edb809ee68c59c1469d28011e2d3be7af1cc5f8ab4d6a994150091983abfa41R544-R558): Added the `replaceDivWithBr` function to remove opening `<div>` tags and replace closing `<div>` tags with `<br>`. Integrated this function into the `parseSheetItemHTML` workflow to enhance the handling of HTML content.## Description
> Clean Divs from sheet texts to prevent white screens

- helm-chart/sefaria/templates/configmap/local-settings-file.yaml
fix for - https://app.shortcut.com/sefaria/story/18766/web-users-are-logged-out-unexpectedly-and-have-to-login-again
Changed the session engine to be cached_db for persistent storage of cache data
> fix(local-settings): update SESSION_ENGINE to use cache_db 

- static/js/BannerImpressionProbe.jsx
- static/js/Header.jsx
- static/js/Misc.jsx
- static/js/ReaderApp.jsx
To help determine the discrepancy issues with Google Analytics, **GA4** events have been added to the same DOM events as Simple Analytics (SA) events. Once data is collected from both firing at the same points, the platforms can be directly compared. **GA version:** GA4 via gtag('event', ...). **Parity:** SA and GA use identical event names/params where supported.
- Adds Simple Analytics events to fire during impressions and interactions for banners/modals.
- Adds **GA4** events to the same DOM events as the previous areas where Simple Analytics events were added.
- Adds a new `BannerImpressionProbe` component that simulates the behavior of a Strapi-driven `Banner` at the same DOM level, emitting both GA4 and SA events when an impression occurs.
- The `BannerImpressionProbe` component is …
> Add Google Analytics events in same locations as Simple Analytics events

- e2e-tests/tests/banner.spec.ts
- static/js/Header.jsx
Fixed the tests that were failing.
They now just check the href is correct and don't click on the links.
I also changed a few more links from `/help` to use direct links.
I also made sure they open in a new tab
> Zendesk link fixes - tests and some final touches

- reader/tests.py
This small PR fixes the `test_new_sheet` test case which is silently ignored due to duplication. 
The PR renames one of the `test_new_sheet` tests. It also fixes a small typo along the way.
> Fix sheets tags test case

- static/js/Editor.jsx
This pull request introduces a small but important change to the `serialize` function in `Editor.jsx` to improve how lists are handled during HTML serialization. The change ensures that when a paragraph does not contain list-related HTML tags, it is wrapped in a `<div>`, which helps the deserializer correctly parse lists.
Improvements to HTML serialization for lists:
* Updated the `serialize` function to wrap paragraph content in a `<div>` unless it already contains list-related tags (`<ul>`, `<ol>`, `<li>`), improving list parsing during deserialization.…ap in divs based on list presence
> preserve wrapping div of lists in serialization

- static/js/Misc.jsx
- static/js/sefaria/util.js
Added logic to save the cookie for the banner to a cookie domain.
So for example, in both  https://modularization.cauldron.sefaria.org/ and https://sheets.modularization.cauldron.sefaria.org/ the cookie will be saved in `.cauldron.sefaria.org`
I have added a util func to findLongestCommonSuffix
> Make Cookie banner cookie work across modules.

- static/css/s2.css
The font size was too small.
This was because a patch that reduced the font size to `font-size: 62.5%`
It seems like the core issue was solved so removing the scaling should be OK.
The commit that introduced the [font-size problem](https://github.com/Sefaria/Sefaria-Project/commit/dab6fa7520d1fd3fd9a4a136beddb78f3d04e188)
Fix language-toggle alignment (broke after the initial change) by vertically centering sheet header items.
> Removed the scaling of the sheet page - fixing font size issue

- static/js/ContentText.jsx
This pull request makes a small update to the logic for filtering content in the `VersionContent` component. The change ensures that the filter condition checks for the existence of the `text` property within both `primary` and `translation` objects, rather than just their truthiness.
* Updated the `toFilter` condition in `static/js/ContentText.jsx` to check for `primary?.text` and `translation?.text` instead of just `primary` and `translation`.…ion text
> Fixing Filtering Condition of Inline Images

- static/css/s2.css
This PR includes several CSS changes, all were requested in [this one ticket](https://app.shortcut.com/sefaria/story/37204/library-polish-headers-and-navigation)
These were all the requested changes as summarised by CC (Claude Code):
Cross Platform:
- Translations Module spacing (16px → 6px margin-top)
- Sidebar footer spacing (6px → 16px padding-inline-end)
Desktop Only:
- Site Header dropdown dividers (removed double styling for top and bottom)
- User Menu spacing (added 10px margin-top)
- Language Switcher spacing (added 10px margin-bottom)
- Sign Up Button (added component specific styling)
- Living Library spacing (added 22px margin-top)
- User Menu hover (removed text-decoration)
Mobile Web:
- Recently Viewed module (added 10px padding-bottom)
- Safari logo centering (removed …
> Library polish headers and navigation - CSS changes
